aptos-labs/explorer

src/components/WalletButton.tsx
This PR modifies the wallet button to match dark and light mode
Dark mode
Light mode
=> adjust wallet button to light and dark mode

src/components/GeneralTableHeaderCell.tsx, src/components/GeneralTableRow.tsx, src/components/HashButton.tsx, src/components/TransactionsTable.tsx, src/components/WalletButton.tsx, src/pages/Governance/Proposals/Table.tsx
=> [Governance] unify table UI for Transactions and Proposals

src/api/wallet.ts, src/components/WalletButton.tsx, src/context/wallet/context.tsx, src/context/wallet/useWallet.tsx, src/pages/Governance/Proposals/Instructions.tsx
This PR sets the account created state and lets the user know if they need to create an account by displaying it on the wallet button or the connect step in the instructions section on the proposals page
https://user-images.githubusercontent.com/29798064/183765092-b7d2f965-26a8-4792-bee9-63c4d06c153c.mov
=> [GOVERNANCE] handle create account event

src/GlobalState.tsx, src/api/hooks/useSubmitTransaction.ts, src/api/wallet.ts, src/constants.tsx, src/context/wallet/context.tsx, src/context/wallet/useWallet.tsx, src/pages/layout/NetworkSelect.tsx, src/utils.ts
Before sign and submit a transaction, we want to make sure the explorer and the wallet are set to the same network. 
This PR blocks and returns an error when users try to sign and submit a transaction if the explorer an wallet are not set to the same network
=> [GOVERNANCE] check wallet and explorer use the same network

src/context/wallet/useWallet.tsx
we were setting the wallet network only when a wallet is connected, we should set it on first load and then listen to any network changed event
=> [GOVERNANCE] fix wallet network bug

src/pages/Governance/Proposal/Header.tsx, src/pages/Governance/Proposals/Table.tsx, src/pages/Governance/components/ExecutionStatusIcon.tsx, src/pages/Governance/components/VotingStatusIcon.tsx, src/pages/Governance/utils.tsx
* make execution status helper functions and reuse them in the proposal header and proposals table
* add execution status to proposals table
=> [Governance] add execution status to proposals table

src/pages/Governance/Proposal/Header.tsx, src/pages/utils.tsx
Set 1 minute interval to show proposal time remaining countdown.
Potential follow-up PR: when time ends, update the proposal status, the time remaining, voting card, etc - needs refactoring
=> show proposal time remaining countdown

src/pages/Governance/Proposal/Content.tsx, src/pages/Governance/Proposal/Header.tsx, src/pages/Governance/Proposals/Table.tsx, src/pages/Governance/Types.ts, src/pages/Governance/hooks/useGetProposal.tsx, src/utils.ts
We were missing executed proposals from the UI because the metadata property is gone from the proposal object once the proposal has been executed. 
A new property was introduced to keep the metadata alive https://github.com/aptos-labs/aptos-core/pull/3140/files 
We now get the metadata values as a utf8 string encoded as hex, we need to convert it back to string.
=> handle new proposal metadata property

src/components/Nav.tsx, src/pages/layout/Header.tsx
- Bring back Navigation for Desktop & Mobile
- Adjust spacing of items / breakpoints to better match Marketing site
=> Re-enable Nav (desktop & mobile), match Marketing spacing

src/api/hooks/useSubmitTransaction.ts, src/api/wallet.ts, src/components/WalletButton.tsx, src/pages/Governance/Proposal/card/VoteButtons.tsx, src/pages/Governance/Stake/Index.tsx, src/pages/Governance/hooks/useSubmitStake.ts, src/pages/Governance/hooks/useSubmitVote.ts
Updates to use Petra 0.1.6 version
1. Pass transactions as JSON object to Petra
2. Display Petra's transactions errors
=> Use Petra 1.6 version

src/pages/Governance/Proposal/card/ResultBar.tsx, src/pages/Governance/Proposal/card/ResultsSection.tsx
Per @movekevin's request, this PR added tooltips to show votes on hover. I thought about showing the number statically in the results section, but I really don't want to break Josh's beautiful design. Thus added the votes number in tooltips on hover. Should be sufficient enough.
=> [Governance] show votes on hover

src/components/GoBack.tsx, src/pages/Governance/CreateProposal/Create.tsx, src/pages/Governance/Proposal/Index.tsx
To address feedback from internal test: https://www.notion.so/aptoslabs/WIP-Governance-AIT3-Dogfooding-Instruction-01743af243d44794911aeb46b53cf9d1#82eb7c17671f4e6d9efbe73624be24cb
This PR:
* when a user visits a proposal page by opening url `/proposals/<handle_id>/<proposal_id>`, show go back button and go back to the proposals page on click.
=> [Governance] go back from proposal page

src/api/hooks/useGetAccountResource.ts, src/pages/Governance/Stake/Create.tsx, src/pages/Governance/Stake/components/CreateOrEdit.tsx, src/pages/Governance/Stake/components/EditOperator.tsx, src/pages/Governance/Stake/components/EditVoter.tsx
After users initialize staking pool OR change operator OR change voter, we want to show the new app state (without the need for them to refresh the page)
https://user-images.githubusercontent.com/29798064/186471548-806724a3-5615-4e7f-b0ce-434951c319ea.mov
=> use state to show stake pool, voter, operator changes on the ui

src/pages/Governance/Proposal/HasVotedCard.tsx, src/pages/Governance/Proposal/Index.tsx, src/pages/Governance/Proposal/hooks/useAccountHasVoted.tsx
When the connected account (on Petra) enters a proposal page we want to let them know whether they already voted on that proposal.
When proposal is still open to votes
When proposal is close to votes
When not voted
=> check if account has already voted on a proposal

src/pages/Transactions/helpers.tsx
"0" is used as a placeholder for `null` for timestamps on chain. Therefore, "0" should not be a valid time. This PR fix this problem.
|Before|
|<img width="1583" alt="Screen Shot 2022-08-24 at 7 33 17 PM" src="https://user-images.githubusercontent.com/109111707/186561516-33f28bf1-44d3-405a-9f37-ce20e16d19bc.png">|
|---|
|After|
|<img width="1555" alt="Screen Shot 2022-08-24 at 7 35 04 PM" src="https://user-images.githubusercontent.com/109111707/186561562-74a6c476-193c-4680-8baf-d749dfbfe440.png">|
=> [Governance] fix time is "0"

src/components/HashButton.tsx, src/components/TransactionsTable.tsx, src/pages/Governance/Proposal/Header.tsx, src/pages/Governance/Proposals/Table.tsx, src/pages/Governance/Stake/components/EditOperator.tsx, src/pages/Governance/Stake/components/EditVoter.tsx
A few days ago I added a link for HashButon so that clicking on the expanded hash button will bring us to the account page for that hash. The bug was, the link is set to account page for all hashes. Clicking on a transaction hash button also brings us to account page which is wrong. This PR fixes the bug by adding `type` property for the component `HashButton` and redirecting to the correct page on click.
=> [Explorer] fix hash button link

src/pages/Governance/Stake/components/CreateOrEdit.tsx
To address bug report https://aptos-org.slack.com/archives/C03SS1MMX3K/p1661805542133359.
|Before|After|
|---|---|
|<img width="1402" alt="Screen Shot 2022-08-29 at 4 09 56 PM" src="https://user-images.githubusercontent.com/109111707/187315636-4d764973-e289-47b3-bb8a-b071b7b9f61f.png">|<img width="1401" alt="Screen Shot 2022-08-29 at 4 10 31 PM" src="https://user-images.githubusercontent.com/109111707/187315632-73b0de1e-cc08-4007-913b-834a5acc10c3.png">|
This is a hot fix to show the staking page even when the connected account is not in the right network. 
Ideally, we should prevent users connect their accounts on the wrong network in the wallet extension. This will take some decent effort and some time to wait for Chrome store review. So here we implement this hot fix in the Governance …
=> [Governance] staking page wallet connection hot fix

src/pages/Governance/Stake/components/CreateOrEdit.tsx
This is a follow up of #131. 
Synced up with @kent-white, the new plan is to show error message when the connected account does not exist in the current network. We want to prompt users to switch to the correct account in the wallet app.
=> [Governance] add error message when account does not exist

package.json, src/pages/NodeChecker/Client.tsx, src/pages/NodeChecker/ConfigurationSelect.tsx, src/pages/NodeChecker/EvaluationDisplay.tsx, src/pages/NodeChecker/Index.tsx, src/pages/NodeChecker/hooks/usePortInput.tsx, yarn.lock
The new HandshakeEvaluator requires that the user provides a public key. This change makes it possible for them to do that. The public key field is only shown if necessary.
I tested both remote and local NHCs, each with different baseline configurations that sometimes require the public key. Every use case I tested worked with the UI.
=> [NHC] Add support for specifying public key and noise port if necessary

src/GlobalState.tsx, src/constants.tsx, src/pages/layout/FeatureBar.tsx, src/pages/layout/Header.tsx, src/pages/layout/NetworkSelect.tsx, src/pages/layout/index.tsx
As discussed in https://aptos-org.slack.com/archives/C03NTMWVA6Q/p1662755968130119, I'm looking for a solution to hide in-development features from users. After doing some research on the third-party tools that supports all the fancy things including A/B test and data analysis, I finally landed on an extremely simple and 100% free solution. We will use the param in the URL to identify the current mode (prod/dev). The implementation is similar to how we handle networks. In the future, we can potentially support more features. For example, we might have dev1 and dev2 which gates different in-dev features. 
https://user-images.githubusercontent.com/109111707/189464809-93f1d1ff-a532-40b9-b664-da0a8962ba59.mov
=> [Explorer] add dev mode

src/components/IndividualPageContent/CollapsibleCard.tsx, src/components/IndividualPageContent/CollapsibleCards.tsx, src/components/IndividualPageContent/ContentBox.tsx, src/components/IndividualPageContent/ContentRow.tsx, src/components/IndividualPageContent/EmptyValue.tsx, src/components/IndividualPageContent/JsonCard.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/ChangesTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/PayloadTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
Move some reusable components to global components folder. The following PRs will use them for the account page.
=> [Explorer] re-organize files

src/components/IndividualPageContent/ContentBox.tsx, src/components/IndividualPageContent/ContentRow.tsx, src/components/IndividualPageContent/ContentValue/EmptyValue.tsx, src/components/IndividualPageContent/ContentValue/GasValue.tsx, src/components/IndividualPageContent/ContentValue/TimestampValue.tsx, src/components/IndividualPageContent/JsonCard.tsx, src/components/IndividualPageContent/LearnMoreTooltip.tsx, src/components/IndividualPageContent/TimestampValue.tsx, src/components/StyledTooltip.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx, src/pages/Transaction/helpers.tsx
In this PR:
* reordered fileds in txn Overview tabs
* added tooltips for fields to explain what it is and provide useful links to learn more
* code clean up
=> [Explorer] new txn page: add tooltips

src/components/GoBack.tsx, src/pages/Account/Index.tsx, src/pages/Transaction/Index.tsx
=> [Explorer] hide "Aptos Explorer" header for dev mode

src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/InfoTab.tsx
This PR applies a small design change that was discussed with Giselle offline.
* rename "Overview" => "Info"
* move to the right most
=> [Explorer] move and rename account overview tab

_redirects, src/index.tsx
In this PR: redirect to the new domain `https://explorer.aptoslabs.com/` when users visit `https://explorer.aptoslabs.com/`.
I played with Netlify for a while and couldn't find an easy way to do the redirecting. So here it is. This is apparently not an ideal solution but it works.
=> [Explorer] redirect to the new domain

package.json, src/components/IndividualPageContent/ContentValue/CurrencyValue.test.tsx, src/components/IndividualPageContent/ContentValue/CurrencyValue.tsx, src/components/IndividualPageContent/ContentValue/GasValue.tsx, src/index.tsx, src/pages/Account/AccountInfo/Balance.tsx, src/pages/LandingPage/NetworkInfo/TotalStake.tsx, src/pages/LandingPage/NetworkInfo/TotalSupply.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx, src/pages/Transactions/helpers.tsx, src/utils.ts
Fix a few small issues:
1. Keep rest of URL intact when redirecting from old to new explorer URL
2. Gas prices: show units, unit price, and the total actual spent (and now, in APT!)
https://aptos.dev/concepts/basics-gas-txn-fee/
Max gas (amount) -> maximum number of gas units you want to spend on a txn
Gas used -> number of gas units you spent on a transaction
Gas unit price -> amount (in APT) you want to pay for a single gas unit
Gas fee -> Total number of gas units used * the gas unit price; how much APT of gas total the transaction cost to execute
=> Fix some small issues

src/pages/Block/Tabs/OverviewTab.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/helpers.tsx
This PR added more fields to the block page Overview tab.
=> [Explorer] block page more

src/api/hooks/useGetUserTransactionVersions.ts, src/pages/LandingPage/Index.tsx, src/pages/LandingPage/UserTransactionsPreview.tsx, src/pages/Transactions/TransactionsTable.tsx
Transactions type filtering has not been supported yet. Although we do want users to see user transactions only, at least in the home page. Therefore this PR is a walk around before we have transaction type filtering supported.
=> [Explorer] show user transactions only on home page

public/_redirects
redirect governance endpoints to governance foundation site #194
Test
https://deploy-preview-194--aptos-explorer.netlify.app/proposals should redirect to https://governance.aptosfoundation.org/
=> redirect governance endpoints to governance foundation site

src/api/hooks/useGraphqlClient.tsx, src/api/wallet.ts, src/constants.tsx, src/context/wallet/context.tsx, src/context/wallet/useWallet.tsx, src/index.tsx, src/pages/Blocks/Index.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transactions/Index.tsx
Fixed:
* event key is deprecated and should not be shown
* The Devnet URL network parameter requires an uppercase "Devnet" value unlike the other networks.
* Transactions and Validators have "back" button but Blocks doesnt
* auto redirect to the new governance site
=> [Explorer] fix bugs reported from dogfooding

src/components/GeneralTableRow.tsx, src/components/HashButton.tsx, src/components/IndividualPageContent/JsonCard.tsx, src/components/Nav.tsx, src/pages/Account/Tabs/TokensTab.tsx, src/pages/Account/Tabs/TransactionsTab.tsx, src/pages/Block/Tabs/TransactionsTab.tsx, src/pages/Token/Index.tsx, src/pages/Token/Tabs/ActivitiesTab.tsx, src/pages/Transaction/Tabs/ChangesTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transaction/Tabs/PayloadTab.tsx, src/pages/Validators/Table.tsx
* bolding the tab name visited while on it (Transactions, Block, Validators). 
* show "No Data" card message when no data on Transactions tab on account page (right now it shows an empty table)
* json card:
* limit the max height of the expanded card
* when card is expanded, only the collapse button is clickable, not the whole card
* validators page:
* make validators table not clickable
* table alignment
* validators ordered in voting power
=> [Explorer] fixing bugs from dogfooding

src/api/hooks/useGetBlock.ts, src/api/hooks/useGetTPS.ts, src/api/hooks/useGetTPSByBlockHeight.ts, src/api/index.ts, src/components/IndividualPageContent/ContentRow.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/pages/Block/Index.tsx, src/pages/layout/Search/SearchBlockByHeight.tsx, src/pages/layout/Search/SearchBlockByVersion.tsx
This PR fixed two nits. One was caused by including an icon component (a `<div>`) in a Typography (a `<p>`). The other was caused by querying block with transactions while transactions were not needed.
=> [Explorer] fix warnings

src/ExplorerRoutes.tsx, src/components/HashButton.tsx, src/pages/Account/Components/TokensTable.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/pages/Account/Tabs/TokensTab.tsx, src/pages/LandingPage/UserTransactionsPreview.tsx, src/pages/Token/Index.tsx, src/pages/Token/Tabs/OverviewTab.tsx
As discussed with @bowenyang007, a few token related changes are made in this PR:
* add token Store column in account page tokens table
* add `propertyVersion` as a url param for the token page
* add Owner(s) field for token page
* the old Owner field should really be "Royalty  Payee" and be moved below "Royalty"
=> [Explorer] token related changes

src/api/hooks/useGetInDevMode.ts, src/api/hooks/useGetSearchResults.ts, src/components/Nav.tsx, src/components/NavMobile.tsx, src/components/PageHeader.tsx, src/constants.tsx, src/pages/Account/Index.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/InfoTab.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/pages/Account/Tabs/ResourcesTab.tsx, src/pages/LandingPage/Index.tsx, src/pages/Transaction/Tabs.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/ChangesTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/PayloadTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx, src/pages/Transaction/Title.tsx, src/pages/Transactions/TransactionsTable.tsx, src/pages/layout/FeatureBar.tsx
Yay~ Finally we're releasing the new version Explorer to users. This PR added a new feature `gtm` (get to market) that represent the explorer mode of mainnet launch. `gtm` will be the new default mode. After the new version has been running for a few days and working well, I'll remove the `gtm` flag and make it `prod`. Code clean up will be done by then too.
=> [Explorer] launch new explorer

src/api/hooks/useGetNetworkChainIds.ts, src/constants.tsx, src/pages/LandingPage/Index.tsx, src/pages/layout/NetworkSelect.tsx
* add chain ids in network select button
* hide local network when local is not available
* reorder networks
* remove "NETWORK" in home page header
=> [Explorer] add network chain id

src/components/HashButton.tsx, src/components/HeadingSub.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/pages/Account/Tabs/ResourcesTab.tsx, src/pages/Block/Index.tsx, src/pages/LandingPage/NetworkInfo/Card.tsx, src/pages/LandingPage/NetworkInfo/MetricCard.tsx, src/pages/Token/Tabs/OverviewTab.tsx, src/pages/Transaction/Index.tsx, src/pages/Transaction/Tabs/ChangesTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transactions/AllTransactions.tsx, src/pages/layout/Header.tsx, src/pages/layout/NetworkSelect.tsx
We got a bunch of Sentry errors that are related to conditional hooks. Basically all hooks should be used unconditionally at the top of a component. Any early return will be a violation. This PR scans the code base and fixes (hopefully) all the conditional hooks.
=> [Explorer] fix conditional hooks

src/api/hooks/useGetNetworkChainIds.ts, src/pages/layout/NetworkSelect.tsx
Previously, the implementation of chain ids introduced hooks errors. Because the hooks to get chain id data are rendered conditionally which violates React hooks policy. This PR changed the implementation so that components were rendered conditionally instead of hooks. Will land this PR upon gtm due to business requirements.
=> [Explorer] Chain IDs in network button

src/pages/layout/NetworkSelect.tsx
To address: https://aptos-org.slack.com/archives/C040LV2NWQ4/p1666027289782289?thread_ts=1666024691.510529&cid=C040LV2NWQ4
Hide local the select menu item completely when local is not available.
|Before|After|
|![image](https://user-images.githubusercontent.com/109111707/196250678-bb66af5e-8517-47b4-ba5d-ff77ad2afd32.png)|<img width="312" alt="Screen Shot 2022-10-17 at 10 57 11 AM" src="https://user-images.githubusercontent.com/109111707/196250567-d2d82c1b-8381-41de-bbc4-9513715dfe67.png">|
=> [Explorer] fix network button

src/api/hooks/useGetInDevMode.ts, src/api/hooks/useGetSearchResults.ts, src/components/Nav.tsx, src/components/NavMobile.tsx, src/components/PageHeader.tsx, src/constants.tsx, src/pages/Account/Index.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/InfoTab.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/pages/Account/Tabs/ResourcesTab.tsx, src/pages/LandingPage/Index.tsx, src/pages/Transaction/Tabs.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/ChangesTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/PayloadTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx, src/pages/Transaction/Title.tsx, src/pages/Transactions/TransactionsTable.tsx, src/pages/layout/FeatureBar.tsx
This PR removes code for the old version Explorer. The new version Explorer has been launched under `feature=gtm` for a week. No notable regression. Therefore it's now safe to remove the deprecated code and make the new version `feature=prod`.
=> [Explorer] remove old explorer code

src/pages/layout/Search/Index.tsx
When user type in something in the search bar, for example "0x1", the search bar fetch data for "0", "0x", and "0x1". It's possible that the results of "0" get returned after the results of "0x1" get returned. And the search bar will show the latest results that got returned which is the results of "0". This is not what we want since the user meant to search for "0x1".
There could be potentially a couple of solutions. I decided to do the following based on the performance and complexity of the implementation: we wait for the users to stop typing before fetching the search results. This way "0" and "0x1" won't be searched at all therefore less network requests and better performance.
=> [Explorer] fix search bar

src/pages/Account/Index.tsx, src/pages/Account/Tabs/TokensTab.tsx
When talking to the indexer, we should pass addresses as the format of `0x000...000123`. Before is `0x123` or `123`.
=> [Explorer] update address format for indexer queries

src/api/hooks/useGetAccountAllTransactions.ts, src/pages/Account/Components/AccountAllTransactions.tsx, src/pages/Account/Components/AccountTransactions.tsx, src/pages/Account/Tabs/TransactionsTab.tsx, src/pages/Transactions/TransactionsTable.tsx
Previously, in the account page, we show the transactions where this account is the sender. Users won't be able to see the transactions where they receive coins from other accounts. This PR updates the account transactions table so that ALL transactions that this account is involved in will be shown. 
Next step: add columns like "Sender" and "Receiver"
=> [Explorer] Account all transactions

src/pages/Blocks/Table.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/Components/TransactionBlockRow.tsx, src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
* add block height in transaction page
* reorganize the fields with block row added
* open new tab from clicking the blocks page
=> [Explorer] add txn block

src/pages/Transaction/Tabs/BalanceChangeTab.tsx, src/pages/Transaction/Tabs/EventsTab.tsx, src/pages/Transaction/utils.tsx
This PR fixes the balance change bug reported in:
https://explorer.aptoslabs.com/txn/0x55db875837a67c9568d2481c0e4f9ff4c37b757a8ff2586b341622f2e933defb
The problem is that, in previous implementation, we check all coin Deposit and Withdraw events. But not all coin deposit/withdraw events are APT coins. In this PR, I added an APT check to filter out coin events that are not APT coins. 
| Before |<img width="1517" alt="Screen Shot 2022-11-01 at 4 46 33 PM" src="https://user-images.githubusercontent.com/109111707/199362838-39acfeaf-5555-4eb6-a916-8fd1ee5ef712.png">| After |<img width="1466" alt="Screen Shot 2022-11-01 at 4 46 42 PM" src="https://user-images.githubusercontent.com/109111707/199362836-5439af9e-7af6-4e29-a894-f390cc332814.png">|
=> [Explorer] fix balance change

src/api/hooks/useGetValidatorSet.ts, src/components/Table/GeneralTableHeaderCell.tsx, src/components/TransactionType.tsx, src/pages/Validators/Index.tsx, src/pages/Validators/Table.tsx, src/pages/Validators/ValidatorsTable.tsx
* new validators table for mainnet, including data from the leaderboard https://aptoslabs.com/leaderboard/mainnet?sort=-governance_voting_record
* make validators page sortable by columns
* this change is gated behind dev mode
Next step:
* add tooltips
* add status icons
https://user-images.githubusercontent.com/109111707/199644854-a0d1dec2-a768-4f87-85f6-8089820086f4.mov
=> [Explorer] new validators table

src/components/TransactionStatus.tsx, src/pages/Transaction/Tabs/Components/TransactionFunction.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
* show "script" as function when applicable
* change the padding of transaction status component
=> [Explorer] show "script" when the transaction is a script

src/components/Table/GeneralTableHeaderCell.tsx, src/components/TransactionType.tsx, src/pages/Validators/ValidatorsTable.tsx
=> [Explorer] move table header tooltip icon to the right

src/components/LoadingModal.tsx
`CircularProgress` component was displaying browser focus styling on its container:
https://user-images.githubusercontent.com/98909677/202533710-da657800-1e14-4178-bb1a-0ddefef3954a.mov
Fixed with `outline: '0';` on `div` container:
https://user-images.githubusercontent.com/98909677/202533806-28cc50f4-d6ca-4b5d-b37d-2a1da0647142.mov
=> Removes focus outline on CircularProgress container

src/components/Table/TableTooltip.tsx, src/components/TooltipTypography.tsx, src/components/TransactionType.tsx, src/pages/Validators/Components/Epoch.tsx, src/pages/Validators/Components/LastEpochPerformanceTooltip.tsx, src/pages/Validators/Components/Map.tsx, src/pages/Validators/Components/RewardsPerformanceTooltip.tsx, src/pages/Validators/Index.tsx
* release new validators page to users
* remove blue box on click for map
* address a few design feedback
=> [Explorer] launch new validators page

src/api/hooks/useGetANS.ts, src/api/hooks/useGetSearchResults.ts
* enable name search with `name.apt`. previously only `name` is supported
* show `name.apt` in the search result. previously only the address is shown
=> [ANS] better name search experience

src/pages/Analytics/Components/BarChart.tsx, src/pages/Analytics/Components/LineChart.tsx
Disables `maintainAspectRatio` for Charts, providing more consistent results upon browser resize.
=> Disable "Maintain Aspect Ratio" for Charts

src/components/IndividualPageContent/ContentRow.tsx, src/pages/DelegatoryValidator/DetailCard.tsx
This is a hot fix to revert UI change in #314 that broke explorer content layout.
|Before|After|
|---|---|
|<img width="1263" alt="Screen Shot 2023-01-24 at 6 20 24 PM" src="https://user-images.githubusercontent.com/109111707/214466387-ece3f349-b33e-4143-af42-28ddb30bbf90.png">|<img width="1304" alt="Screen Shot 2023-01-24 at 6 20 14 PM" src="https://user-images.githubusercontent.com/109111707/214466409-81d1d3b4-32cf-4e8e-bf85-23b5f6a74591.png">|
=> [Fix] revert content row UI

src/pages/DelegatoryValidator/Components/MyDepositsStatusTooltip.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/constants.ts
had some issues to the step number icon color override. will refactor later.
=> [explorer][delegation] add status tooltip stepper

src/api/hooks/useGetMainnetValidatorsGeoData.ts
validators page fail to load due to country potentially being null for this validator
=> [explorer][hot-fix] validators page geoData null issue

src/pages/DelegatoryValidator/Components/MyDepositsStatusTooltip.tsx, src/pages/DelegatoryValidator/Components/StakingStatusIcon.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx
share this step status across tooltip and table row.
=> [explorer][delegation] add status icon to my deposits section

src/pages/DelegatoryValidator/Components/TimeDurationIntervalBar.tsx, src/pages/DelegatoryValidator/DetailCard.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakeDialog.tsx, src/pages/DelegatoryValidator/UnstakeDialog.tsx, src/pages/DelegatoryValidator/WalletConnectionDialog.tsx, src/pages/Validators/Index.tsx, src/pages/Validators/ValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/215843907-763aa198-e369-450d-88fe-7c06a22c04ac.mov
couple things this pr addressed:
1. on the validators page, the tab has underline colors previously. pr updated to get rid of the color and remain consistent with tab usages in other places
2. lockedUtilSecs could be nullable. check it whether it's null or not before hands. this eliminates the error in the react console.
3.  make details page skeleton mobile friendly
4. address react console warning on dialog font size complain: "h5 can't be in h2"
5. short term sol:  persist the dev param in the url from the validators page to the validator page
=> [explorer][delegation] address some nits

src/pages/Validators/Components/Epoch.tsx
WP-289
https://user-images.githubusercontent.com/121921928/215924185-ce220243-2f8f-45ad-938e-9b8a70d44918.mov
jsyk, me playing around with react inspector has nothing to do with the page reloading, its just the timing.
=> WP-289 fix Epoch over 100% if page's not reloaded

src/components/IndividualPageContent/ContentValue/CurrencyValue.tsx, src/pages/Analytics/Charts/DailyGasConsumptionChart.tsx
this value should be total daily gas consumed in APT. according to the data source from this [chat thread](https://aptos-org.slack.com/archives/C040LV2NWQ4/p1675115093212439), we don't need to set decimal as 8 cuz its already pre-computed in 
```
select date(timestamp) ds, sum(t.gas_used*ut.gas_unit_price)/1e8 gas_cost
from `indexer_mainnet_gcp.transactions_view` t  
join `indexer_mainnet_gcp.user_transactions` ut 
on t.version = ut.version
where t.success = true
group by 1 order by 1
```
=> [explorer][analysis] fix the value format in Gas Consumption chart WP-296

src/GlobalState.tsx, src/api/hooks/useGetValidators.ts, src/api/hooks/useSubmitStake.ts, src/api/hooks/useSubmitTransaction.ts, src/components/AmountTextField.tsx, src/components/snakebar/ErrorSnackbar.tsx, src/components/snakebar/FailureSnackbar.tsx, src/components/snakebar/TransactionResponseSnackbar.tsx, src/constants.tsx, src/pages/DelegatoryValidator/StakeDialog.tsx, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx, src/pages/DelegatoryValidator/hooks/useAmountInput.tsx, src/pages/layout/FeatureBar.tsx, src/pages/layout/NetworkSelect.tsx
commit: 61458b187089068f17cd5dc0c405ed52a052a0de
1. use governance stake txn submission hooks and other utils like stake amount validation, snakebar for errors, etc.
2. adding more screen recording to demo the change
https://user-images.githubusercontent.com/121921928/219195648-f8abb20d-3fa6-452a-a344-807900f13033.mov
https://user-images.githubusercontent.com/121921928/219198213-ec490043-6d01-4a36-b642-be5ceca73c13.mov
https://user-images.githubusercontent.com/121921928/219195800-0ebf0f19-9b28-4136-a313-b9ffc9b98801.mov
https://user-images.githubusercontent.com/121921928/219195780-d1936ab1-5a1c-4310-90d1-bbe90f8bb1e5.mov
-------
1. add aptos client to the global state so that we don't need to create it every time we need it
2. add transaction succeeded dialog
3. enable staking flow …
=> [explorer][delegation] enable staking

src/api/hooks/useGetDelegatorStakeInfo.ts, src/api/index.ts, src/pages/DelegatoryValidator/Components/StakingStatusIcon.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/index.tsx
| --------------- | --------------- |
| <img width="153" alt="Screenshot 2023-02-16 at 12 20 28 PM" src="https://user-images.githubusercontent.com/121921928/219478049-dc93f6fe-0a37-46c2-9756-ee5415630994.png"> | <img width="375" alt="Screenshot 2023-02-16 at 12 23 16 PM" src="https://user-images.githubusercontent.com/121921928/219478644-13369568-d872-4d4f-bb02-1d8327969abf.png"> |
1. get the stake info from sc view functions so that now we have (active, inactive, pending_inactive) stake info for a delegator
2. modify the my deposit section to use this stake info
=> [explorer][delegation] fresh out my deposit sections with staking info

src/api/hooks/useGetDelegatedStakeOperationActivities.ts, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/utils.tsx
[gdoc that's helpful to understand the logic here](https://docs.google.com/document/d/1aTZv7su2FW0mNVDxz5b48-WsOkw3GhZ551Petr4-StM/edit#heading=h.bm8uprtpmfww)
[slack thread that discusses this in depth](https://aptos-org.slack.com/archives/C04EXV6UTR7/p1676623842397019)
```
Step 1: 
get total amount of (active, inactive, pending_inactive) from get_stake
Step 2:
Calculate “principal”
Active_principal
Loop through all events in sequence (transaction_version asc, event_index asc)
Maintain a current active_principal variable, start with 0
Every time you see AddStakeEvent, add to active_principal
Every time you see UnlockStakeEvent, subtract from active_principal
Every time you see ReactivateStakeEvent, add to active_principal
If at any point during the loop active_principal < 0, reset to 0 …
```
=> [explorer][delegation] add rewards earned computation

src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/index.tsx
change the default my deposits section skeleton loading to be `connected`. 
* when wallet not connected, default will be false, so that its not loading
* when wallet connected, default will be true, and loading will be turned to false once variables loaded
https://user-images.githubusercontent.com/121921928/220478127-8099dcb0-5117-4ff3-b42b-419a7780fa11.mov
=> [explorer][delegation] fix the forever loading when wallet not connected issue

src/api/hooks/useSubmitStakeOperation.ts, src/pages/DelegatoryValidator/StakeOperationDialog.tsx
stake amount is bigint, it can only take amount thats in the signed bigint range. however, it's easy to exceed that limit and overflow. right now, this pr used `toFixed(8)` to handle the limit but its not ideal.  open for suggestions on how to better handle this situation. 
https://user-images.githubusercontent.com/121921928/220262873-83a21638-b7a3-472f-92b2-3fa76381a7e2.mov
https://user-images.githubusercontent.com/121921928/220262878-ce6aa345-3d26-4357-a755-b2d6aca20299.mov
=> [explorer][delegation] handle bigint overflow when submitting txn

src/api/hooks/useGetDelegationNodeInfo.ts, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/Validators/DelegationValidatorsTable.tsx, src/pages/Validators/Table.tsx, src/pages/Validators/ValidatorsTable.tsx
before, we were using validator voting power for delegatedStakeAmount, which is wrong. now we get the right amount for staking from [account resources](https://fullnode.testnet.aptoslabs.com/v1/accounts/0x5df905f817adf39293c596e83512ab8a9dc5a19980e11bd4ce44b6e749d33a0d/resources) delegation pool's total coins.
=> [explorer][delegation] fix delegatedStakeAmount

src/pages/DelegatoryValidator/MyDepositsSection.tsx
so when users stake, they will be charged with `add_stakes` fee which will make their amount less than their stakes. when computing rewards, its possible that `amount - principal < 0`. in this case, return `N/A`
https://user-images.githubusercontent.com/121921928/221298157-88dc3842-b786-4060-90f9-6a925fc47509.mov
=> [explorer][delegation] fix negative rewards issue

src/api/hooks/useGetANS.ts, src/api/hooks/useGetSearchResults.ts, src/utils.ts
With ANS primary name launching, we want to show primary names for the accounts instead of a random name when there're multiple names under one account.
* when you have a primary name, show the primary name
* when you don't have a primary name, just show one of the names you own
* when you own multiple names, you can search with any of the name, but the primary name will be attached on the side of address in the search result
=> [ANS] show primary name

src/api/hooks/useGetSearchResults.ts, src/components/TitleHashButton.tsx
=> [ANS] show .apt after names in account title and search result

package.json, src/api/index.ts, src/pages/Account/Tabs/ModulesTab.tsx, src/utils.ts, yarn.lock
I suggest visiting https://deploy-preview-362--aptos-explorer.netlify.app/account/0x1/modules?feature=dev before reviewing this PR. This should give you a good understanding of what the current PR does.
Summary:
1. Add `ModulesContentReworked` that implements the new view code design
2. In `ModulesTab`, display `ModulesContentReworked` only if `inDev`
3. In `ModulesContentReworked`, display both source code and ABI
=> [explorer] add source code to modules tab

src/components/hooks/useExpandedList.ts
the issue here is that we the initial value provided to `useEffect` is not reflected without the first render, by using `useEffect`, it's essentially enforcing to update the  `expandedList` when `count` changes.
but it's slightly anti-pattern cuz we use props as the change factor to trigger `useEffect`. open to other suggestions. 
[reference](https://thewebdev.info/2021/03/14/how-to-fix-the-react-usestate-hook-not-setting-initial-value-problem/)
https://user-images.githubusercontent.com/121921928/223313036-4c48c056-7bf5-4562-9d01-414aadb50639.mov
=> [contract] fix missing EXPAND | COLLAPSE on modules tab

src/pages/Account/Tabs/ModulesTab.tsx
=> [explorer] show no-code msg if source code unavailable

src/context/color-mode/ProvideColorMode.State.ts
This fix sets the default color scheme to the user's system settings if not previously toggled. 
You can test in Dev Tools by clearing all LocalStorage and making a selection under `Emulate CSS media feature prefers-color-scheme` within the Rendering tab.
=> [explorer] Set default color scheme to system if not specified

src/context/color-mode/ProvideColorMode.State.ts
Update logic for initial color scheme to utilize `window.matchmedia` API + fix for needing to click toggle twice upon initial interaction.
=> [explorer] Set initial color scheme to utilize window.matchmedia API

src/api/hooks/useGetDelegationState.tsx, src/components/AmountTextField.tsx, src/pages/DelegatoryValidator/DetailCard.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx, src/pages/DelegatoryValidator/constants.ts, src/pages/DelegatoryValidator/hooks/useAmountInput.tsx, src/pages/DelegatoryValidator/utils.tsx
*0x1 delegation_pool contract is not deployed to testnet yet, so in the testing, we can't actually see what's gonna happen if 10apt min requirement's not met at the pool level. will perform more real testing once 0x1's actually released.*
1. create a new hook to consolidate some delegation state that are used in multiple places
2. create the util function to compute for min, max, suggested max per stake operation
2.1. **min**: minimum APT to move around, hard enforced
2.2. **suggested max**: suggested maximum APT to move around in order to not enforcefully move all funds away from the pool, soft enforced
2.3. **max**: max APT to move around, hard enforced
3. use **11** APT as the UI minimum for operations, because we have two scenarios that will make 10 APT enforcement on UX difficult: 1) …
=> [delegation] make changes to comply with 10 min apt enforcement

src/pages/DelegatoryValidator/StakingBar.tsx
to make it consistant in the staking bar with another APT amount
=> [nit] change decimal

src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/hooks/useAmountInput.tsx
Safari was showing blank screen with the syntax error: `Invalid regular expression: invalid group specifier name` most likely due to positive lookbehind assertion `(?<=...)` used in the regular expression within `replace()`, which doesn't seem supported in Safari.
Modified with a function to separate the logic of removing non-digit characters from the logic of removing extra decimal points. 
Before:
After:
=> [delegation] Fix Safari blank screen due to regular expression error

src/pages/Account/Tabs/ModulesTab.tsx
=> [explorer] fix code block circle radius

src/pages/Account/Tabs/ModulesTab.tsx
=> [explorer] fix circle radius in expanded code block

.gitignore, src/api/hooks/useGetDelegationNodeInfo.ts, src/api/hooks/useSubmitStakeOperation.ts, src/api/index.ts, src/constants.tsx, src/pages/Validators/DelegationValidatorsTable.tsx, src/pages/Validators/ValidatorsTable.tsx
1. use 0x1 since delegation's in released in testnet
2. first check whether validator has delegation pool before querying all the delegation related info. so that we don't run into tons of network errors that will lead to 429
3. use whitelisted validator address again so that we can avoid querying view function on whether delegation pool exists or not for all validators, to save network query.
=> [delegation] update testnet delegation address to 0x1

src/ExplorerRoutes.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/ModulesTab.tsx
/account/0x1/modules/code
/account/0x1/modules/write
/account/0x1/modules
/account/0x1/resources (still working)
=> [explorer] refactor modules tabs to reuse existing pattern

src/components/IntervalBar.tsx
temp mitigation on the constant refreshing issue in delegation validator page to exclude the window reload for delegation use case.
for the specific validator, `0xfd47a2fb988c959839ea2fe4d7169b48536a42bf5e4933790701a08252ba2039` on 0x1, lockup cycle already ends and doesn't get updated to a new lockup cycle. so window.reload is constantly triggered.
i'm working on a long-term solution rn.
=> [delegation] fix constant refreshing

src/components/IntervalBar.tsx
- when lockup cycle only exists in the past, meaning that validator's no longer active and lockup cycle will not get updated anymore. this pr is to add this edge case in.
- need to use view function to check whether funds are withdrawble. cuz once validator is in inactive status, funds will not be moved from pending_inactive to inactive pool automatically, since the move is initiated with epoch change and lockup cycle change but lockup cycle will not be changed for inactive validators.
=> [delegation] add inactive validator scenario for countdown bar

src/api/index.ts, src/pages/DelegatoryValidator/MyDepositsSection.tsx
Return whether `pending_inactive` stake can be directly withdrawn from the delegation pool, for the edge case when the validator had gone inactive before its lockup expired.
=> [delegation] make funds withdrawable when validator becomes inactive

src/pages/Account/Tabs/ModulesTab.tsx
from lex: Secondary button height is 36 px. Should be 32. Expand code button should be 32x32
before
after
=> [explorer] fix copy code button and expand code button style

src/components/CodeLineBox.tsx, src/components/IndividualPageContent/JsonCard.tsx, src/components/IndividualPageContent/JsonViewCard.tsx, src/pages/Account/Tabs/ModulesTab.tsx, src/themes/colors/aptosColorPalette.ts
=> [explorer] use the same background color for source code and json view

src/pages/Account/Tabs/ModulesTab.tsx
lex: Why do we have a different modal size for expanded code? And different left padding?
0xbe1:
1. this PR fixes the different modal size issue by changing `maxWidth` to `width`
2. different left padding: the left padding is actually the same, but why do you see the inconsistency? it is because the "line number" column determines its width based on the max line number. For example, if the module has 1000 lines of code, then the whole line number column has the width for 4 numbers `xxxx`. However, if the module has just 50 lines of code, then the column saves the space for only 2 numbers `xx`. I am not sure what's the desired behavior here, so I haven't fixed it in this PR
---
before
after
=> [explorer] fixed code modal width

src/pages/Account/Tabs/ModulesTab.tsx
=> [explorer] fix modules page sidebar text style

src/components/IntervalBar.tsx
- once we have a list of inactive validators, will signal in the validator page that this validator is inactive and avoid showing the tooltip.
=> add tooltip to countdown interval when it is completed

src/api/index.ts, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx
context: after syncing with external partners, we've decided collectively to enforce 11 min APT and add_stake fee's deducted from this 11 min. 
---
this PR involves 3 changes
1. add add_stake fee info to the staking dialog so that delegators are aware of the fee.
2. refactor inactive pool withdraw experience
3. migrate from `<text>` to `<span>` to avoid the error in console
https://user-images.githubusercontent.com/121921928/228945204-59f32f31-a50a-42a9-afc5-1319ff9215d9.mov
https://user-images.githubusercontent.com/121921928/228945234-0eaee634-18a0-42e9-a781-496b3d63c2ac.mov
=> [delegation] refactor inactive withdraw and add add_stake fee info

src/api/hooks/useGetDelegatedStakingPoolList.ts, src/pages/DelegatoryValidator/Components/StakingStatusIcon.tsx, src/pages/DelegatoryValidator/index.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
even though some validators were never active, they are also delegation validators, (which's achieved by running CMD to create delegation pool sc).
these validators should also get listed up in the explorer so that they still get the chance to receive stakes even though these stakes won't generate rewards at all.
https://user-images.githubusercontent.com/121921928/230229594-f7af4f1d-5369-4bce-a692-8a9d6a257006.mov
=> [delegation] add completely inactive delegation validators

src/api/hooks/useGetANS.ts, src/components/TitleHashButton.tsx
This reverts commit 512e58dacf5648068fde91175c1e8d75648e1d95.
cache caused it keeps displaying the first name for all following account user viewed.
=> Revert "[GP-209] cache ANS name for owner in account page (#442)"

src/api/hooks/useGetANS.ts, src/components/TitleHashButton.tsx
**Background**
We previously try to cache ANS name to reduce API call to indexer. But there were some issues.
**Solution**
We need to cache in `useEffect` otherwise we are caching the previous value because useState is not synchronous.
Since we only cache the account owner's ANS name, it shouldn't add too much data to `localStorage`, chatgpt said if average string length is 50 char, `localStorage` should be able to hold 100_000 strings.
=> fix ANS caching

src/ExplorerRoutes.tsx, src/components/CodeLineBox.tsx, src/components/Table/GeneralTableCell.tsx, src/components/router-link.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/ViewCode.tsx, src/pages/Transaction/Tabs/Components/TransactionFunction.tsx, src/pages/Transactions/TransactionsTable.tsx, src/pages/utils.tsx, src/themes/colors/aptosColorPalette.ts
This PR implements deep linking from entry function links in the transaction list and transaction details to the corresponding module and function name.
Often times when looking at a list of transactions it's useful to do what this transaction was actually doing by looking at the source code.
Currently it takes 5+ mouse clicks (to get the corresponding module) + several keystrokes (to copy&paste the function name and find it in the source code) in rather unintuitive places to get from a function name to it's definition. This PR reduces this in the ideal case to essentially 1 single mouse click.
1. Introduced a new Link component that tries to use Copyable Links / hrefs vs programmatic navigation so that users can right-click a URL and copy it or open it in a new tab vs having to actually …
=> [code view] Implement deep linking to module and function name

package.json, pnpm-lock.yaml, src/components/AmountTextField.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/DelegatoryValidator/hooks/useAmountInput.tsx, src/pages/DelegatoryValidator/index.tsx, src/pages/DelegatoryValidator/utils.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
1. stake
1. active validator
1. current 0 in active pool
1. if < 11, stake disabled, can’t stake
2. if > wallet balance, stake disabled, can’t stake
2. current have > 10 in active pool
1. if stake amount + current < 11, stake disabled
2. if stake amount + current > 11 and stake amount < wallet balance, stake enabled
3. if stake amount > wallet balance, stake disabled
3. if wallet balance + active pool < 11, stake disabled
2. inactive validator
1. same to active validator except that unlock date row is removed
2. TODO: remove add stake fee row as well
2. unstake
1. active validator
1. pending_active has more than 10
1. unstake < 10, warning will tell total amount will be unstaked, unstake enabled
2. unstake more than what’s staked, warning will tell total amount will be unstaked, unstake …
=> [delegation] fix and feedback addressing

README.md, package.json, src/api/hooks/useGraphqlClient.tsx, src/components/HashButton.tsx, src/components/snakebar/FailureSnackbar.tsx, src/pages/Account/Components/TokensTable.tsx, src/pages/Account/Tabs/ModulesTab/ViewCode.tsx, src/pages/Analytics/NetworkInfo/NetworkInfo.tsx, src/pages/Block/Tabs/OverviewTab.tsx, src/pages/Blocks/Table.tsx, src/pages/Token/Component/ActivitiesTable.tsx, src/pages/Token/Tabs/OverviewTab.tsx, src/pages/Transaction/Tabs/Components/TransactionBlockRow.tsx, src/pages/Transaction/Tabs/Components/TransactionFunction.tsx, src/pages/Transactions/TransactionsTable.tsx, src/pages/Validators/StakingDrawer.tsx, src/pages/layout/Footer.tsx, src/pages/layout/Header.tsx, src/pages/layout/Search/ResultLink.tsx, src/routing.tsx
This generalizes the `InternalLink` component into the `Link` component that can be used everywhere, incl. external links.
We do so by skipping link augmentation if the `to` parameter points to an external origin.
This fixes the broken nft metadata links such as https://explorer.aptoslabs.com/token/7c8d820c87ad860e42dfff3b3a6b8e1eb4f305fb3228d3facf4ef13a33fdd68b/0?network=mainnet which accidentally used the InternalLink component and broke the external metadata link.
Now we don't have to worry anymore where to use <Link> vs <InternalLink>, everything can just use the`<Link>` component from routing.tsx.
In addition to this I removed the style overrides (such underline="none") from within the Link component and moved them to the call-site when removing underline etc. is actually desired. …
=> [GP-2] fix external links by enhancing/generalizing InternalLink component to Link and use it everywhere

src/api/hooks/useGetDelegationNodeInfo.ts, src/pages/Account/Error.tsx, src/pages/DelegatoryValidator/Components/ValidatorStatusIcon.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/constants.ts, src/pages/DelegatoryValidator/hooks/useAmountInput.tsx, src/pages/DelegatoryValidator/index.tsx, src/pages/Validators/Components/Staking.tsx, src/pages/Validators/DelegationValidatorsTable.tsx, src/pages/Validators/Index.tsx
1. make staking and unstaking warning message more accurate.
- if active pool has less than 10 apt after txn, unlock all
- if pending_inactive pool has less than 10 apt after txn
- if active pool has enough stake, unlock 10 apt to meet minimum requirement, else unlock all
2. update tooltip wording on apy, and staking status
3. update validator state to reflect all 4 states
4. fix the txn succeeded dialog amount mismatch issue: https://aptos-org.slack.com/archives/C04EXV6UTR7/p1681942876524159
5. fix withdraw action when validator's inactive to check for both withdraw and pending_inactive fund 
| -- | -- |
| <img width="456" alt="Screenshot 2023-04-19 at 5 01 31 PM" src="https://user-images.githubusercontent.com/121921928/233224379-74fc4b7d-3759-478f-b639-1ee018925a7b.png …
=> [delegation] address mainnet testing feedback

src/pages/DelegatoryValidator/Components/ValidatorStatusIcon.tsx, src/pages/DelegatoryValidator/Title.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
previously validator state's queried inside a different component, might cause mismatch when table's reordered.
=> [delegation] fix validator state mismatch issue

src/api/hooks/useGetValidators.ts
issue reported from partner: https://aptos-org.slack.com/archives/C03BE1CFFR8/p1682106982957519
> Hi! Just noticed the such thing - the explorer does not show our validator name. And the link to it leads here - https://explorer.aptoslabs.com/account/0x639fd7e993d9fbdee08e96a77b0fc6cde10d0636fa289382812124156738348  And if you look at the information through aptos names, then here - https://explorer.aptoslabs.com/account/0x0639fd7e993d9fbdee08e96a77b0fc6cde10d0636fa289382812124156738348
It seems that the problem is that the address starts with 0?
as well as issue reported on github: https://github.com/aptos-labs/explorer/issues/480
=> [EZ] add operator address padding as well

package.json, pnpm-lock.yaml, src/index.tsx, tsconfig.json
This upgrades wallet adapter to the latest version which includes (https://github.com/aptos-labs/aptos-wallet-adapter/pull/129) which fixes the wallet auto reconnect. Removing the now obsolete window.onload workaround so that the page loads+renders at normal speed again.
Tested locally the wallet connnection flow + refresh a few times and it works as expected.
Also making some minor edits to the tsconfig.json (in particular removing isolatedModules: true) which makes VS Code properly suggest auto imports of other modules which didn't work previously.
=> upgrade wallet adapter and remove wallet connection drop workaround

src/ExplorerRoutes.tsx, src/api/index.ts, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/pages/Account/Tabs/ModulesTab/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/ViewCode.tsx, src/pages/Transaction/Tabs/Components/TransactionFunction.tsx
as we're about to add read and write, the current routes for /modules doesn't work.
current:
/account/:account/modules/:module
proposed:
/account/:account/modules/:action/:module (action is one of "code", "read" and "write")
see https://deploy-preview-483--aptos-explorer.netlify.app/account/0x1/modules/code/account?network=mainnet for an example
=> [explorer] /modules default to /modules/code

src/pages/Account/Tabs/ModulesTab/Contract.tsx
Clear all of the states in the Form component when `fn` changes. So that we can avoid bugs like:
- Query result isn't cleaned after changing the selected `fn`
- Args are not cleaned after changing the selected `fn`
=> [Code View&Run] Clear state when function changed

src/ExplorerRoutes.tsx, src/__tests__/utils.test.ts, src/pages/Account/Components/SidebarItem.tsx, src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/pages/Account/Tabs/ModulesTab/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/ViewCode.tsx, src/pages/Transaction/Tabs/Components/TransactionFunction.tsx, src/utils.ts
#501 
Before this change, only the "code" tab on the modules page align the URL with the tab state. 
For example: `http://localhost:3000/account/0x1/modules/code/acl?network=devnet&feature=dev`
After this change, the "run" and "view" tabs will also align the URL with the tab state. But for the "run" and "view" tabs, the sidebar item is a function in a module, instead of the module itself.
So the link would be: `http://localhost:3000/account/0x1/modules/view/${moduleName}/${functionName}?network=devnet&feature=dev`
And when switch between tabs, we will keep the URL state. For example:
-  If the user is looking at the `balance` function in the `coin` module, which is `http://localhost:3000/account/0x1/modules/view/coin/balance?network=devnet&feature=dev`.
-  Then the user switches to the …
=> [Code View&Run] Router for Run and View contract

src/api/hooks/useSubmitTransaction.ts, src/pages/Account/Components/CodeSnippet.tsx, src/pages/Account/Tabs/ModulesTab/Contract.tsx
Run Success, click the "View transaction" can go to the transaction page.
Run Failed
View Success
View Failed
Disable the button to avoid repeated execution, and show a spinner:
=> [Contract] Add contract execution result

.eslintrc.cjs, index.html, package.json, pnpm-lock.yaml, src/api/hooks/useGoogleTagManager.ts, src/components/IndividualPageContent/ContentValue/CurrencyValue.test.tsx, src/constants.tsx, src/index.tsx, src/utils.test.ts, tsconfig.json, tsconfig.node.json, vite.config.ts
This migrates from [create-react-app](https://github.com/facebook/create-react-app) which is kinda abandoned to using https://vitejs.dev/ . For further motivation see https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o .
The main motivation I'm making this change is that the stacktraces in production are pretty unreadable since create-react-app transpiles async functions to older JS syntax even though that's unnecessary with our target browsers and create-react-app is not configurable for this.
But also create-react-app seems abandoned anyways.
I followed mostly this guide for the migration https://www.robinwieruch.de/vite-create-react-app/ .
Bonus: I added some very basic eslint setup - currently only enforcing rules of hooks. Turns out we have a quite number of violations of …
=> migrate from abandoned create-react-app to vite

src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/utils.ts
We can test on this account in testnet: 0x3d097bb505c9e5d8a96e367f371168240025877f6be8d4a88eacaafb709fe5c9.
After this change, we support user input hex or array for `vector<u8>`.
Meanwhile, I figured out that the BCS serialization for `view` function is not necessary, so I removed that code.
`view` function can accept `vector<u8>` as hex. `submit` function can accept `vector<u8>` as an array of strings.
I haven't tested vector type other than `vector<u8>`. I will deploy some contracts to test to see if it's the same. When I figured it out, I will make a new PR to fix other types.
=> [Contract] Fix bool & vector for contract execute

package.json, pnpm-lock.yaml, src/components/IndividualPageContent/ContentValue/GasValue.tsx
The wallet adapter [updated to include deep linking support](https://github.com/aptos-labs/aptos-wallet-adapter/pull/149). This PR updates our version to use the new adapter, as well as fixes a lingering import issue with `react-number-format`. [Here is the upgrade guide](https://s-yadav.github.io/react-number-format/docs/migration/) for `react-number-format` for reference. 
I smoke tested to make sure the tests in the previous PR work when including the new npm modules:
https://github.com/aptos-labs/explorer/assets/694324/c5718364-246c-4e61-89ce-6332b0f523ac
=> Updates wallet-adapter and react-number-format

src/pages/Account/Tabs/ModulesTab/Contract.tsx
Some entry function does not have the `signer` param. We should also support that.
=> Support entry function without signer param

src/pages/LandingPage/Components/PlaygroundBanner.tsx, src/pages/LandingPage/Index.tsx
=> [playground] add playground marketing banner gated with flag

src/pages/Token/Tabs/OverviewTab.tsx
Nodereal noticed that their ANS name was showing previous owners and suggested a fix of limiting the query.
**Before:**
**After:**
=> Limits token owners

src/api/hooks/useGetSearchResults.ts, src/constants.tsx
Whenever querying a account address we would show account and object in the search prefill.
This PR changes the logic so we only so the object result when the account has an object core resource
NOTE: The assumption that Account's can't have ObjectCore is incorrect. But this should fix the dupe results for most cases.
https://github.com/aptos-labs/explorer/assets/19931667/3bcdeead-5acd-422a-9e34-065d961ecb88
=> Fix for showing dupe for account and objects

src/pages/DelegatoryValidator/Components/ValidatorStatusIcon.tsx, src/pages/DelegatoryValidator/Title.tsx, src/pages/DelegatoryValidator/utils.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
http://localhost:3000/validators/delegation?network=mainnet
=> Hide inactive validators without any delegated stake

src/index.tsx, src/pages/LandingPage/Components/PlaygroundBanner.tsx
This was causing significant loadtimes that were blocking the content from loading. Once playgrounds is live we can put this back in another way.
=> Remove statsig waitforinit

src/pages/Account/hooks/useLogEventWithBasic.ts, src/pages/Validators/Index.tsx, src/utils.ts
We will hopefully move off of statsig logging in the coming weeks, so I don't want to think too hard about a better solution
=> Fix for not waiting for initialization of statsig

src/api/hooks/useGetAccountAllTransactions.ts, src/api/hooks/useGetAccountTokens.ts, src/api/hooks/useGetDelegatedStakeOperationActivities.ts, src/api/hooks/useGetNumberOfDelegators.ts, src/pages/Account/Tabs/CoinsTab.tsx, src/pages/Transaction/utils.tsx, src/utils.ts
See the amounts shown for this bad address
http://localhost:3000/account/0x0628e72def46bc247908f0b06367bfbf744a50328e429a97632941035ef50a63/transactions?network=mainnet
Future Work:
We can do this better to normalize coming from the node, but I didn't want to try and figure that out today without more testing, so this is a bandaid solution with a little bit of cleanup
=> Normalize address's for transactions

src/pages/DelegatoryValidator/StakeOperationDialog.tsx
Add extra warning when attempting to stake in a pool with 100% comission.
not 100% commision
100% commision
=> Add warning for 100% commision

src/utils.ts
Inputting into a vector: `[]` will now provide an empty vector instead of the vector `[""]`
=> [Module] Allow Run contract to use empty arrays

src/pages/Analytics/Charts/MonthlyActiveUserChart.tsx, src/pages/Analytics/Components/LineChart.tsx
Having 0 decimals on a chart with 1M made it impossible to understand the axis. So we need to add a decimals place.
No change for the other charts
=> Add decimals to axis for large numbers

src/api/index.ts, src/pages/Account/Tabs/ModulesTab/Contract.tsx
I found this useful in debugging a view function for a user.  View functions are allowed to run on any ledger version, so this adds functionality to the explorer to use it.
https://github.com/aptos-labs/explorer/assets/1335270/2cae303a-0019-4919-8daa-acf14228b36c
=> [view] Add ledger version to be used as an input for view functions

src/api/hooks/useGetDelegationNodeInfo.ts, src/api/index.ts, src/components/Banner.tsx, src/pages/Account/Components/AptosNamesBanner.tsx, src/pages/DelegatoryValidator/index.tsx, src/pages/LandingPage/AptosLearnBanner.tsx, src/pages/Validators/CommissionChangeBanner.tsx, src/pages/Validators/Index.tsx, src/pages/Validators/StakingBanner.tsx, src/pages/Validators/StakingDrawer.tsx
[Ticket](https://linear.app/aptoslabs/issue/WAL-898/%5Bexplorer-chore%5D-show-commission-rate-changes#comment-b59046de)
Dunno about the language, and yall might not like that mustard yellow pill button 😗 
There was still an FAQ in the codebase, updated it just in case
Just need a double check on my logic
I hardcoded a new rate to demonstrate the banner on the individual banner page. The banner won't show up on individual validator pages if the upcoming rate is the same as the current rate
https://github.com/aptos-labs/explorer/assets/694324/011328aa-ed36-4dd8-b439-cbbef5aa4066
=> Adds banners to notify commission changes are impending

src/api/hooks/useGetDelegationNodeCommissionChange.ts, src/api/hooks/useGetDelegationNodeInfo.ts, src/pages/DelegatoryValidator/index.tsx
[My previous PR](https://github.com/aptos-labs/explorer/pull/650) introduced a regression, causing the delegation page to hit rate limits. I added an additional `view` to [`useDelegationNodeInfo`](https://github.com/aptos-labs/explorer/compare/inc-31?expand=1#diff-ae78229edfd40cc88cd35326bd4731041f41fde373b63acacb9af87949c8526aL47-L51) which bumped us from O(2n) `view` calls on that list page to O(3n). That coupled with the growing list of validators tipped us over the limit. 
This highlights the fragility of the current solution. We should invest some time refactor the queries to use more recently introduced indexer tables.
=> Alleviates rate limiting issue on explorer delegation validators page

src/pages/layout/index.tsx
As mentioned by msafe, reinitializing the wallet adapter, that is expected to have static state can have strange side effects. I've applied this to all wallets integrated with the explorer, that don't take in network specific information.
=> [wallets] Statically initialize wallets that don't change for networks

src/api/hooks/useGetDelegationNodeCommissionChange.ts, src/api/index.ts
Copy pasta issues from a previous hotfix to repair the validator page from crashing
=> Fixes issue where commission change wasn't showing up

src/components/IndividualPageContent/ContentValue/TimestampValue.tsx, src/pages/Block/Tabs/OverviewTab.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx, src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx, src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx, src/pages/utils.tsx
Summary
Time stamps are kind of wacky coming back from the node. The request here was to not format expiration_timestamp because its user inputted. The previous logic was interesting and seemingly can come back from the node in a different fashion.
Test plan
http://localhost:3000/txn/369869258?network=mainnet
=> Fix for expiration timestamp formatting issues

src/pages/DelegatoryValidator/index.tsx
@kaw2k unsure of when next commission can be null but it seems to be happening a lot.
[
](url)
no more banner when its null: http://localhost:3000/validator/0x9bfd93ebaa1efd65515642942a607eeca53a0188c04c21ced646d2f0b9f551e8?network=mainnet
banner on prod: /validator/0x9bfd93ebaa1efd65515642942a607eeca53a0188c04c21ced646d2f0b9f551e8?network=mainnet
=> Fix for commision rate change showing even though the next commission is null

src/components/HashButton.tsx, src/pages/Account/Error.tsx, src/pages/Account/Index.tsx, src/pages/Token/Tabs/OverviewTab.tsx
This adds two functionalities:
1. View tokens for an address if it's not an account or object
2. Add links for token and collection objects directly on the token page for tokenv2.
=> [account] Allow nonexistent account with tokens

src/pages/Analytics/utils.ts
https://explorer.aptoslabs.com/analytics?network=mainnet
Will fix this more thoughtfully in a folllowup but this stops Explorer from not rendering anything.
Renders - http://localhost:3000/analytics?network=mainnet (though some data is missing)
=> Fix for analytics crashing

src/constants.tsx
This is part of the migration to API Gateway. More context here: https://www.notion.so/aptoslabs/Migration-1-Legacy-URL-to-API-Gateway-migration-b007742490684b9bab3debd674504a94.
I found the initial files to change like this:
```
rg -l -e 'fullnode\.[a-z]{3,4}net.aptoslabs.com'
```
I then did a find replace from `fullnode.([a-z]{3,6}net).aptoslabs.com` to `api.$1.aptoslabs.com`.
I did some further digging, e.g. for places where we perhaps build the URL, by just looking at every file that references `aptoslabs.com`. Hopefully this is everything.
I haven't touched indexer API, we'll do that in another PR.
I didn't touch randomnet or previewnet.
CI for now.
=> Use node API via API Gateway

src/api/hooks/useGraphqlClient.tsx
This is part of the migration to API Gateway. More context here: https://www.notion.so/aptoslabs/Migration-1-Legacy-URL-to-API-Gateway-migration-b007742490684b9bab3debd674504a94.
I found the initial files to change like this:
```
rg -l 'aptoslabs.com'
```
In the preview you can see that a page that relies on the indexer works, e.g. the tokens page for an account: https://deploy-preview-679--aptos-explorer.netlify.app/account/0x232098630cfad4734812fa37dc18d9b8d59242feabe49259e26318d468a99584/tokens?network=mainnet. It uses the new URL correctly.
=> Use indexer API via API Gateway

src/api/hooks/useSubmitTransaction.ts
[bugfix] Resolved bug resulting from differing name conventions of the local testnet between Explorer and wallet SDK.
An Explorer user can not run entry functions on-page against their local testnet, due to the conditional network name check. Local testnet had two different names across Explorer and the wallet SDK ("local" and "localhost", respectively), so the check always fails.
I updated the conditional to convert any mention of the Explorer's "local" network into "localhost", during the check. Now, the conditional is properly applied.
Performing a string replacement in this single instance requires fewer modifications across both codebases.
=> Fix Explorer and wallet SDK network name comparison for local testnet

src/ExplorerRoutes.tsx, src/pages/Account/Index.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/pages/Account/Tabs/ModulesTab/Tabs.tsx, src/pages/Account/Tabs/ModulesTab/ViewCode.tsx, src/pages/Account/Tabs/ModulesTab/index.tsx
This is temporary, ideally we should make an `/address` and simply decide on that page between object and account. Many of the redirects will probably not work correctly from transactions and other places until that is done.
Example here https://deploy-preview-690--aptos-explorer.netlify.app/object/0x3a473af845d46da6356b6d02d7ebf6ecbc62224a0b96407f6c3d2e8502b2b7d3/modules/code/composable_nfts?network=devnet
=> [object] Add support for code as objects

src/pages/Account/Tabs/ModulesTab/ViewCode.tsx
**Bug**
Got this [error](https://aptos-labs.sentry.io/issues/5114792971/?project=6249755&referrer=github-pr-bot) on sentry, turns out this account published an empty package. 
[Here's an account with empty package](https://explorer.aptoslabs.com/account/0xbd27b6ddb1b58075df6f7199bb68506e0fd20b142171e6b2b2c0ea232773f5aa/modules?network=testnet). If you switch to module tab, the explorer is broken.
**Fix**
Treat empty package as no package.
=> Fix module tab when package is empty

src/components/IntervalBar.tsx
Resolves #614
---
**What's the issue?**
Text inside the `IntervalBar` component wraps when the text length is too long.
---
**Solution**
If `days` are greater than `10`, we can remove the `seconds` value to shorten the string and ensure it fits inside the bounds.
---
**Solution screenshots**
|Before|After|
|--|--|
|![](https://github.com/aptos-labs/explorer/assets/12480362/8231c551-c579-4e56-9f67-f8092778b07d)|![](https://github.com/aptos-labs/explorer/assets/12480362/b6ec83da-34d9-48d3-9a21-60e74fb51834)|
---
**Alternative solutions**
|Description|Screenshot|
|--|--|
|Increase bar width by 20px|![](https://github.com/aptos-labs/explorer/assets/12480362/5c64d60c-187d-4a01-86a7-9843a0d881a0)|
|Use `white-space: nowrap`|![](https://github.com/aptos-labs/explorer/assets/12480362/2e434b98-1d6d …
=> fix: prevent interval bar text wrap

src/pages/Validators/Components/Epoch.tsx
Once randomness is enabled, epoch time will be 2h + DKG time (<30s).
Ignoring the DKG time when displaying the epoch progress/remaining time.
=> epoch countdown update for randomness

src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/utils.ts
Use `JSON.parse` to handle parsing `[]` arguments. 
Previously, `[[abc]]` would be parsed as `["[abc]"], but really, it should be `[["abc"]]`.
The noteworthy change here is that quotes must now be used for literals. E.g. `[0xabc]` used to be acceptable but now must be specified as `["0xabc"]`
=> Support nested vector in explorer

src/pages/Account/Tabs/ModulesTab/Contract.tsx
This supports two types:
basic inputs 5, 6, 7 or a, b,c
And JSON
[5,6,7] ["a", "b", "c"]
It additionally fixes all options, nested vectors etc.
View functions still probably need some work
You can test the preview page for this same path:
https://deploy-preview-728--aptos-explorer.netlify.app/object/0xdc325741bcf1b2d9bc1de2acf466f1b48ff3de8a39ec82f805fd019d4eb1fc1c/modules/run/wallet_tester/test_bool?network=testnet
=> [run-function] Fix run functionality, add instructions

src/pages/Transaction/helpers.tsx
I'm going off the definitions from here: https://aptos.dev/concepts/blockchain/#proposing-the-block
Would it be accurate to say that the timestamp is right before step 8? (Consensus → Execution)
=> Update block timestamp

src/api/hooks/useGraphqlClient.tsx, src/constants.tsx
Internal context: https://www.notion.so/aptoslabs/Route-more-traffic-through-staging-8ac50da7dfcf490fb329b14d9359c6ee.
In short, we want to route more traffic through the staging API Gateway so it is a representative test environment. The explorer is an important but not critical product and a good candidate for this initiative.
=> Use staging API Gateway for devnet and testnet

src/api/hooks/useGetAccount.ts, src/api/hooks/useGetAccountModule.ts, src/api/hooks/useGetAccountModules.ts, src/api/hooks/useGetAccountResource.ts, src/api/hooks/useGetAccountResources.ts, src/api/hooks/useGetAccountTransactions.ts, src/api/hooks/useGetBlock.ts, src/api/hooks/useGetCoinSupplyLimit.tsx, src/api/hooks/useGetDelegatorStakeInfo.ts, src/api/hooks/useGetMostRecentBlocks.ts, src/api/hooks/useGetTPS.ts, src/api/hooks/useGetTransaction.ts, src/api/hooks/useGraphqlClient.tsx, src/api/index.ts, src/constants.tsx, src/global-config/GlobalConfig.tsx, src/pages/Account/Tabs/ModulesTab/Contract.tsx, src/pages/Analytics/NetworkInfo/TotalTransactions.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakeOperationDialog.tsx, src/pages/DelegatoryValidator/StakingBar.tsx, src/pages/LandingPage/TransactionsPreview.tsx, src/pages/Transaction/Index.tsx, src/pages/Transactions/AllTransactions.tsx, src/pages/layout/Search/Index.tsx
We want to make the explorer start attaching API keys to requests to API Gateway. This way we can identify the traffic more easily and do other smart things to be discussed elsewhere.
While here I also address some misconfiguration where the v2 TS SDK client is created using the default URLs, rather than the URLS in `networks` and `getGraphqlURI` like we want.
I also make the hooks use the pre-existing client rather than build a new one, since the new clients were made without any of the intended configuration. I make the ApolloClient include a key too (woof we build clients in lots of places).
Further context: https://aptos-org.slack.com/archives/C040LV2NWQ4/p1718884516800459.
I gave the keys effectively unlimited ratelimit (2 billion requests per 5 minutes). Each IP is still subject to …
=> Configure explorer to use API keys from API Gateway

src/api/index.ts, src/constants.tsx
This fixes the bug with the dropdown not loading up all the networks: https://aptos-org.slack.com/archives/C040LV2NWQ4/p1718911297644989?thread_ts=1718884516.800459&cid=C040LV2NWQ4.
The typechecker did not catch that I was passing a string where a client was required, something about `[]` into an object I guess doesn't result in a strong type. The new type bound I added on `networks` makes the previous bug an actual type checking error. This helped me confirm there are no other issues similar to this still floating around.
=> Fix useGetChainIdAndCache

src/api/index.ts, src/pages/Account/Error.tsx, src/pages/DelegatoryValidator/Title.tsx, src/pages/DelegatoryValidator/utils.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
This PR attempts to fix the too many requests issue in the Delegation Nodes tab. Uses an immutable Move helper: https://explorer.aptoslabs.com/account/0xafb5ec0d4cc58dbb1034c2a6d977919f50bc2936dc478274d64c08491c119c4a/modules/view/helpers/pool_address_info?network=testnet
Also fixes the "To many requests" copy
=> Batch delegation nodes API call

src/api/hooks/useGetAccountAPTBalance.ts, src/api/hooks/useGetDelegationState.tsx, src/api/index.ts, src/pages/Account/BalanceCard.tsx, src/pages/DelegatoryValidator/MyDepositsSection.tsx, src/pages/DelegatoryValidator/StakingBar.tsx
This now uses the view function, rather than resources to get the APT balance.
=> [balance] Fix APT balance on account page by using view function

src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx, src/pages/Transaction/utils.tsx
@ying-w found a transaction with both null `owner_address` as well as associated `asset_type`. This PR adds null checking and an empty state for that case. Note the asset type on the second row is gone for the amount. Also, the address on the far left is absent. Previously this would just crash the page.
=> Handles potentially null states for coin balance changes

src/pages/Account/Tabs/ModulesTab/Contract.tsx
With modules that don't obey certain rules, they can show no ABI. In that event, the page will go blank, and this fixes it by handling null with undefined
Resolves: https://github.com/aptos-labs/explorer/issues/799
=> [run/view] Fix null ABI to not show blank page

src/pages/Account/Tabs/ModulesTab/Contract.tsx
Without this, you get an error saying `T0` cannot be parsed as a type tag.  This allows generics to be run as functions.
=> [run-function] Fix type tag parsing to allow generics

src/api/client.ts, src/pages/Account/Error.tsx, src/pages/Account/Index.tsx
As found in sentry, this is one of the number one errors, where there's an invalid account address, and an unhelpful message appears.  Now, it gives a simple error
=> [account] Add proper handling for invalid account addresses

src/pages/layout/Search/Index.tsx
This PR updates the search logic to always take you to the target address of the name in question, and if that isn't present it tries the owner address of the name. Previously it would take two searches, first to get the name, then the primary name of the owner of the original name. 
Petra names were not showing up in the search bar. This was a combination of issues:
1. An existing issue with the indexer and ans contract
2. We were using an outdated ANS query that was held on to by the TS SDK
3. We had not appended `.apt` to the search text before passing it to the TS SDK.
NOTE: This won't work until `1` gets resolved.
=> Fixes petra names not showing up in search

src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx, src/pages/Transaction/utils.tsx
Now, there's a type column, which has the event name.  We can make it simpler to say "deposit" or "withdraw", but this should be simple for now.
Resolves: https://github.com/aptos-labs/explorer/issues/783 by fixing which account has a gas fee
https://deploy-preview-808--aptos-explorer.netlify.app/txn/1770138261/balanceChange?network=mainnet
Example with fee payer
=> [balance changes] Fix fee payer, and remove confusing gas column

src/components/IndividualPageContent/ContentValue/TimestampValue.tsx, src/pages/utils.tsx
Really large timestamps weren't parsable, so we say it's greater than the largest possible time.
Resolves: https://github.com/aptos-labs/explorer/issues/237
See https://explorer.aptoslabs.com/txn/7602763?network=mainnet
=> [txn] Fix really large timestamp

src/pages/layout/Search/Index.tsx
Fixes missing transaction by version search
=> [search] Add transaction by version back in

src/pages/Transaction/Tabs/Components/TransactionFunction.tsx
Avoid crashing for multisig execution functions
=> Don't crash if txn doesn't have function

src/api/hooks/useGetCoinList.ts, src/components/HashButton.tsx, src/pages/Transaction/Tabs/BalanceChangeTab.tsx, src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx, src/pages/Transaction/utils.tsx
To differentiate between known coins and unknown coins, it will now pull from the Panora coin list to give more information.
Note that, right now, this is a beta feature... There are FAs that are actually migrated coins that need to be updated in the feature.
Partially resolves https://github.com/aptos-labs/explorer/issues/826
Follow-ups:
1. Coin details page
2. FA details page
3. Coin balances on accounts page
=> [coin balance changes] Add coin balance change verification

src/pages/Transaction/Tabs/BalanceChangeTab.tsx
Previous PR missed the balance change page, but it fixed the overview
=> [balance change] Hide storage refund on balance change page

src/pages/DelegatoryValidator/DetailCard.tsx, src/pages/Validators/DelegationValidatorsTable.tsx
Indexer query returns all delegator balances (table items) associated with pool (not doing event parsing) so will include reward accounts
=> Update num delegator tooltip

.eslintrc.cjs, index.html, package.json, pnpm-lock.yaml, src/themes/theme.ts
@ying-w noted that `,` and `.` were not distinct in the current monospace font. I pulled in `DM Mono` which is the standard monospace font the design system uses. In the process of modifying the `index.html` file our linter started to fail on the doctype tag. Instead of ignoring it, I opted to pull in `eslint-plugin-html` to parse it.
Note, we are currently using adobe for one font and google fonts for another. We should move fully to the design system's fonts at some point. 
New Font
Old Font
=> Updates monospace font

src/api/hooks/useGetANS.ts, src/components/HashButton.tsx, src/components/TitleHashButton.tsx
This provides the ability for verified names, separate of ANS.  ANS name lookups are skipped, and it provides a verification check icon to show that it's a verified name.
For now, I've only provided 0xA as a tester.
An example here: https://deploy-preview-835--aptos-explorer.netlify.app/account/0x000000000000000000000000000000000000000000000000000000000000000a?network=mainnet
=> Verified names

src/components/HashButton.tsx
|before|after|
|---|---|
|<img width="1411" alt="image" src="https://github.com/user-attachments/assets/f54bb548-a821-4945-8eb3-ed91097a4181">|<img width="1427" alt="image" src="https://github.com/user-attachments/assets/935380c4-794a-495a-a7cb-25320f3f5f07">|
=> [HashButton] add margin between img and label

src/components/TransactionType.tsx, src/pages/Transactions/Components/TransactionTypeTooltip.tsx
=> [transaction types] Update logos, and update tooltip to list all

src/components/HashButton.tsx, src/pages/utils.tsx
The tooltip shows the whole ANS name
=> [name] Shorten ANS names down to a shorter name

src/pages/Account/Components/CoinsTable.tsx
|before|after|
|--|--|
|<img width="1424" alt="image" src="https://github.com/user-attachments/assets/9841d43a-bd4b-45f2-8bea-c36fe956962a">|<img width="1419" alt="image" src="https://github.com/user-attachments/assets/c044838f-b30d-4295-afcf-2fccefa5f77c">|
currently, coins page is filled with spam coins, hard to see what what coins matter even with the verified logo.
add "verified | all" tabs and default to "verified" so that only verified coins are displayed by default. only show the rest unless we really want to and click "all"
the UI is pretty much copied from CollapsibleCards.tsx, only modifying text "expand all | collapse all" to "verified | all"
=> [CoinsTable] allow filter by verified

src/api/hooks/useGetCoinList.ts, src/components/Table/VerifiedCell.tsx, src/pages/Account/Components/CoinsTable.tsx, src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx, src/pages/Transaction/helpers.tsx, src/pages/layout/Search/Index.tsx, src/pages/layout/Search/ResultLink.tsx
This adds the ability for hardcoded coins that may not be in the Panora coin list for faster response time.  It also cleans up verification level tooltips, and makes sure all coins show on non-mainnet by default
=> Add hard coded coins

src/pages/layout/Search/Index.tsx
"apt" remains as is
"thala" prefix search works
=> [Search] label search does prefix match if len(searchText) >= 4

src/pages/Transaction/Tabs/ChangesTab.tsx
This is helpful for looking up by resource type, since resource type in Data row is not always fulltext and make ctrl+f search difficult.
Note that in "Before", ctrl+f "AccountPositions" doesnt work, but it works in "After"
|Before|After|
|--|--|
|<img width="1398" alt="image" src="https://github.com/user-attachments/assets/02cfdc10-7223-47de-abe9-3c7ecd1e0a51">|<img width="1392" alt="image" src="https://github.com/user-attachments/assets/f85b2360-c215-4838-8395-08d22d2d9871">|
=> [ChangesTab] add "Resource" row for write_resource change

src/api/hooks/useGetANS.ts, src/components/Table/VerifiedCell.tsx, src/components/TitleHashButton.tsx, src/pages/Coin/Title.tsx, src/pages/FungibleAsset/Title.tsx
Now colors for verification levels:
Balance change example:
https://deploy-preview-877--aptos-explorer.netlify.app/txn/1761043867/balanceChange?network=mainnet
Banned coin example:
https://deploy-preview-877--aptos-explorer.netlify.app/coin/0xbbc4a9af0e7fa8885bda5db08028e7b882f2c2bba1e0fedbad1d8316f73f8b2f::ograffio::Ograffio?network=mainnet
Verified coin example:
=> [verification] Add colors to levels, and say the level in words

src/pages/Coin/Title.tsx
=> [CoinTitle] fix style

src/api/hooks/useGetAnalyticsData.ts, src/api/hooks/useGetFullnodeCount.ts, src/pages/Analytics/NetworkInfo/ActiveFullnodes.tsx, src/pages/Analytics/NetworkInfo/NetworkInfo.tsx
Adds fullnode approx count to the page
=> [analytics] Add fullnode count

src/api/hooks/useGetCoinActivities.ts, src/api/hooks/useGetCoinHolders.ts, src/pages/Coin/Index.tsx, src/pages/Coin/Tabs/HoldersTab.tsx, src/pages/Coin/Tabs/TransactionsTab.tsx, src/pages/FungibleAsset/Index.tsx, src/pages/FungibleAsset/Tabs/HoldersTab.tsx, src/pages/FungibleAsset/Tabs/TransactionsTab.tsx
Added bare minimum associated transactions.  To combine data, we'd need to be able to query multiple transactions 
Follows up on an item from https://github.com/aptos-labs/explorer/issues/906
=> Fixup coin holders page / Add transactinos

src/api/hooks/useGetCoinPairedFa.ts, src/api/hooks/useGetFaPairedCoin.ts, src/pages/Coin/Index.tsx, src/pages/Coin/Tabs.tsx, src/pages/Coin/Tabs/InfoTab.tsx, src/pages/FungibleAsset/Index.tsx, src/pages/FungibleAsset/Tabs/InfoTab.tsx
In /coin page, if paired FA exists, shows it.
In /fungible_asset page, if paired Coin exists, shows it.
lzUSDC Coin https://deploy-preview-916--aptos-explorer.netlify.app/coin/0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC?network=mainnet
lzUSDC FA https://deploy-preview-916--aptos-explorer.netlify.app/fungible_asset/0x2b3be0a97a73c87ff62cbdd36837a9fb5bbd1d7f06a73b7ed62ec15c5326c1b8?network=mainnet
USDt https://deploy-preview-916--aptos-explorer.netlify.app/fungible_asset/0x357b0b74bc833e95a115ad22604854d6b0fca151cecd94111770e5d6ffc9dc2b?network=mainnet
=> [Coin][FungibleAsset] add paired coin/fa info

src/components/hooks/usePageMetadata.ts, src/pages/Account/Title.tsx, src/pages/Analytics/Index.tsx, src/pages/Block/Index.tsx, src/pages/Block/Title.tsx, src/pages/Blocks/Index.tsx, src/pages/Coin/Title.tsx, src/pages/DelegatoryValidator/Title.tsx, src/pages/FungibleAsset/Index.tsx, src/pages/FungibleAsset/Title.tsx, src/pages/LandingPage/Index.tsx, src/pages/Token/Index.tsx, src/pages/Token/Title.tsx, src/pages/Transaction/Title.tsx, src/pages/Transactions/Index.tsx, src/pages/Validators/Index.tsx
Adds titles to each page, I'm not sure I really know what I'm doing here with all the use effects, but it does seem to work decently.
I observed google searches don't give good title names, so adding this will help the google web crawler to give better names
=> [titles] Add updating titles to each pages

src/components/Table/VerifiedCell.tsx, src/pages/layout/Search/Index.tsx
Previously, it's possible though rare, to somehow make a coin that doesn't match emojis, this ensure it only does checks if it's actually emojis.
=> [verification] Ensure emojicoin addresses only match emojis

src/api/hooks/useGetCoinSupplyLimit.ts, src/pages/Analytics/NetworkInfo/TotalSupply.tsx, src/pages/Coin/Index.tsx, src/pages/Coin/Tabs.tsx, src/pages/Coin/Tabs/InfoTab.tsx, src/pages/FungibleAsset/Tabs/InfoTab.tsx
If a coin is verified to not have mint and burn, but they forgot to set the supply, we can manually set the supply here.
Example https://deploy-preview-931--aptos-explorer.netlify.app/coin/0x268d4a7a2ad93274edf6116f9f20ad8455223a7ab5fc73154f687e7dbc3e3ec6::LOON::LOON?network=mainnet
=> [coin] Add ability to override coin supplies for verified coins

src/constants.tsx
Verifies uptos's supply.  No mints had occurred after initial mint.
=> [supply] Verify uptos supply

src/constants.tsx
All uptos pump coins are 1 billion supply, but were not tracked on-chain until a contract upgrade a few days later.
=> [supply] Fix Nruh supply

src/pages/utils.tsx
Fixes LP coin lookup, and more complex coin names
=> [search/coin] Fix LP coin lookup and linking

src/api/hooks/useGetANS.ts
Fixes [https://github.com/aptos-labs/explorer/security/code-scanning/2](https://github.com/aptos-labs/explorer/security/code-scanning/2)
To fix the problem, we should avoid directly embedding user-provided values in the format string. Instead, we can use the `%s` specifier in the format string and pass the untrusted data as corresponding arguments. This approach ensures that the user-provided values are treated as strings and not as format specifiers.
- Modify the `console.error` call on line 107 of `src/api/hooks/useGetANS.ts` to use `%s` specifiers.
- Pass the `address` and `networkName` variables as additional arguments to the `console.error` function.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 2: Use of externally-controlled format string

src/api/hooks/useGraphqlClient.tsx, src/pages/Transactions/Index.tsx
Hello!
Fix back navigation in transactions page
For the first navigation to transactions, a replacement is used so that you can exit with one click
Navigations between user and all transactions work as usual
**Before:**
https://github.com/user-attachments/assets/249dcf58-1e16-4a82-840b-f9003621f296
**After**
https://github.com/user-attachments/assets/bd34345c-d35e-4aa4-81da-a34e0cba64b7
**Thanks!**
=> [txns] Fix navigation in transactions with back

src/pages/Account/Index.tsx, src/pages/Account/Tabs.tsx, src/pages/Account/Tabs/CoinsTab.tsx, src/pages/Account/Tabs/InfoTab.tsx, src/pages/Account/Tabs/ResourcesTab.tsx, src/pages/Account/Tabs/TransactionsTab.tsx, src/pages/Account/Title.tsx
This removes repeated account resources queries.  It removes the constant refresh on deleted resources, adds object ownership info easily accessible as well, and should handle mixed account / object.
Resolves https://github.com/aptos-labs/explorer/issues/957
=> [account] Fix refreshes, and reduce excess API queries

src/components/HashButton.tsx, src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx, src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
https://deploy-preview-987--aptos-explorer.netlify.app/txn/2199584346?network=mainnet
before
after
---
before
after
=> [HashButton] add AssetHashButton

src/pages/Transaction/Tabs/EventsTab.tsx
Resolves https://github.com/aptos-labs/explorer/issues/997
=> [events] Fix invalid event placeholder

src/pages/layout/Footer.tsx
Updated the Twitter URL from https://twitter.com to https://x.com/youngbuddha108 to reflect the platform's rebranding.
=> fix: update Twitter URL to x.com format

src/api/hooks/useSubmitTransaction.ts
When users are using a wallet (Petra) set to localnet and set Explorer to localnet, they are having `Wallet and Explorer should use the same network to submit a transaction` error
The wallet adapter uses "local" as the network name, so no need to add the conversion to "localhost"
=> Fix transaction submission against local testnet

src/pages/Blocks/Table.tsx
For some reason, only one comes back, instead of an array.  Need to dive further, but this keeps the page from crashing on first load
=> [blocks] Fix page on first load

src/components/IndividualPageContent/ContentRow.tsx
The "Total supply" text in the browser currently fails to align properly due to the presence of an icon, which really looks unprofessional.
fixed
=> Style: Improve layout of value display in ContentRow component

src/pages/layout/Search/Index.tsx
This was a case where sometimes it added together to guess to be a deleted object, but it's not.  So, we'll just call it an "address" instead.
=> [account] Treat "deleted object" as a generic address instead

.github/workflows/lint-and-test.yaml
Potential fix for [https://github.com/aptos-labs/explorer/security/code-scanning/9](https://github.com/aptos-labs/explorer/security/code-scanning/9)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will set the `contents` permission to `read`, which is sufficient for the linting and testing steps in this workflow. This change ensures that the workflow adheres to the principle of least privilege and avoids granting unnecessary write permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 9: Workflow does not contain permissions

src/pages/Account/Components/CoinsTable.tsx, src/pages/Account/Tabs/CoinsTab.tsx
Adds conditional buttons for migrating to FA
1. Only enables button if it's not migrated
2. Only enables button if it's your account (the connected one)
3. Doesn't enable if it's FA
=> [coins] Add migration to FA buttons

src/pages/Account/BalanceCard.tsx
Added an external link on the Account page that opens the corresponding Lighthscan page to help users visualise DeFi positions.
More info on Lightscan: https://aptos.lightscan.one
=> feat: add lightscan link on account page

analytics/daily_block_gap.sql, src/api/hooks/useGetAnalyticsData.ts, src/pages/Analytics/Charts/DailyBlockGapChart.tsx, src/pages/Analytics/MainnetAnalytics.tsx
Block gap is a way to measure block production rate. For every day, this is the median time in ms between blocks
=> Add block time to analytics page

src/ExplorerRoutes.tsx, src/pages/Account/Tabs/ModulesTab/Tabs.tsx
In the AccountPage's ModulesTab, navigation issues occur when users switch between the packages tab and other tabs (code/run/view):
https://explorer.aptoslabs.com/object/0x6febdb5695dab42c3edf6baaebf7b49b4ae32fbb1411a5c33917f442ebe77daa/modules/packages/RegulatedToken?network=mainnet
From packages to other tabs: Package names are incorrectly passed as module names, causing other tabs to fail displaying content
From other tabs to packages: Module names are incorrectly passed as package names, causing the packages tab to fail displaying content
URL redirect issues: Frequent URL redirects cause page flickering, degrading user experience
Implemented intelligent navigation conversion logic that performs appropriate parameter conversion based on tab types:
1. Route Optimization …
=> Fix module navigation between packages and other tabs in AccountPage
