aptos-labs/explorer

- src/pages/Governance/Proposal/card/ConfirmationModal.tsx
- src/pages/Governance/Proposal/card/VoteButtons.tsx
- src/pages/Governance/constants.tsx
https://user-images.githubusercontent.com/109111707/183500006-51ecef69-803d-48c2-91c2-592c1f5c380d.mov
| | Dark | Light |
|---|---|---|
| FOR | <img width="408" alt="Screen Shot 2022-08-08 at 10 42 52 AM" src="https://user-images.githubusercontent.com/109111707/183500140-811fddc9-c3a2-413d-9717-3259e600e519.png"> | <img width="444" alt="Screen Shot 2022-08-08 at 10 42 08 AM" src="https://user-images.githubusercontent.com/109111707/183500172-c10ec60a-5989-4d52-90fe-f8858e7421e7.png"> |
| AGAINST | <img width="405" alt="Screen Shot 2022-08-08 at 10 43 37 AM" src="https://user-images.githubusercontent.com/109111707/183500218-9345e13e-dfde-4143-963d-11a461c259da.png"> | <img width="405" alt="Screen Shot 2022-08-08 at 10 43 58 AM" src="https://user-images.githubusercontent.com/109111707/1835003 …
> [Governance] Vote confirmation modal

- src/pages/Governance/CreateProposal/Create.tsx
- src/pages/Governance/Proposal/Content.tsx
- src/pages/Governance/Proposal/ContentRow.tsx
- src/pages/Governance/Proposal/card/ConfirmationModal.tsx
- src/pages/Governance/Proposal/card/ResultBar.tsx
- src/pages/Governance/Types.ts
- src/pages/Governance/hooks/useGetProposal.tsx
1. Update metadata to: https://www.notion.so/aptoslabs/Proposal-data-41061f6166ab4763a8b5f231560b8d53
2. Dark/light mode for the Results bar:
3. Fix `Failed prop type` error.
> [Governance] Update metadata and more

- src/pages/Governance/Proposal/Header.tsx
- src/pages/Governance/Proposal/card/Index.tsx
- src/pages/Governance/Proposals/Table.tsx
- src/pages/Governance/utils.tsx
* proposals table: add icon for status column
* proposal page header
* add icon for status
* hide "Time Remaining" when the proposal is closed
* proposal page 
* hide vote buttons when the proposal is closed
> [Governance] proposal status

- src/api/wallet.ts
fix for sentry error `Cannot read properties of null` due to window.aptos is not ready yet
https://sentry.io/organizations/aptos-labs/issues/3488980419/?project=6249755&referrer=slack
> fix for when window.aptos is undefined

- src/api/hooks/useAddressInput.tsx
- src/api/hooks/useAmountInput.tsx
- src/components/AddressTextField.tsx
- src/components/AmountTextField.tsx
- src/pages/Governance/Proposal/card/Section.tsx
- src/pages/Governance/Proposal/card/VoteButtons.tsx
- src/pages/Governance/Stake/Index.tsx
- src/pages/utils.tsx
https://user-images.githubusercontent.com/109111707/184001296-51dec86a-284b-4c57-a44a-9e613f5ca60f.mov
> [Governance] inputs validation

- src/pages/Governance/Stake/Index.tsx
> [Governance] disable submit button when wallet is not connected

- src/constants.tsx
- add sherrynet fullnode to explorer to make internal testing easier
> update explorer to prepare for internal testing

- src/api/hooks/useSubmitTransaction.ts
- src/constants.tsx
- src/pages/Governance/Proposal/card/VoteButtons.tsx
- src/pages/Governance/Stake/Index.tsx
- src/pages/Governance/components/LoadingModal.tsx
- src/pages/Governance/hooks/useSubmitStake.ts
- src/pages/Governance/hooks/useSubmitVote.ts
https://user-images.githubusercontent.com/109111707/184724362-a9991a7e-2406-4114-970c-26b6c45db1c1.mov
> [Governance] add loading spinner for transactions

- src/pages/Governance/components/snackbar/FailureSnackbar.tsx
- src/pages/Governance/components/snackbar/TransactionResponseSnackbar.tsx
Displays the transaction failed reason on the snack bar
> Display transaction error reason

- src/api/hooks/useAmountInput.tsx
- src/api/hooks/useGetAccountResources.ts
- src/components/AmountTextField.tsx
- src/pages/Accounts/Account.tsx
- src/pages/Governance/Stake/Index.tsx
- src/pages/Governance/Stake/hooks/useAmountInput.tsx
- src/pages/Governance/hooks/useGetProposalsTableData.ts
Pull the minimum/maximum staking amount from chain and validate user input on initializing staking pool
> Stake min max from chain config

- src/pages/Governance/Proposal/Index.tsx
Adds a Back button (to all proposals page) if they come from there
> add back button to proposals page

- src/components/HashButton.tsx
- src/pages/Governance/Proposal/Header.tsx
> [Governance] show proposer address as a hash button

- src/pages/Governance/Proposal/Content.tsx
- src/pages/Governance/Proposal/ContentRow.tsx
- src/pages/Governance/Proposal/Header.tsx
- src/pages/Governance/Types.ts
- src/pages/Governance/utils.tsx
```
- VotingStatus:
- PENDING
- FAILED (not enough votes)
- REJECTED (more no votes)
- PASSED (more yes votes)
- ExecutionStatus
- WAITING_TO_BE_EXECUTED
- EXECUTED
```
WAITING_TO_BE_EXECUTED
EXECUTED
REJECTED
> add proposal voting and execution status

- src/pages/Governance/hooks/useSubmitStake.ts
following this PR https://github.com/aptos-labs/aptos-core/pull/3015/files, changes needed
> rename to initialize_stake_owner

- src/pages/Governance/Proposal/Header.tsx
- src/pages/Governance/Proposals/Table.tsx
> [Governance] replace proposal creation time with voting expiration time

- package.json
- src/api/hooks/useSubmitTransaction.ts
- src/api/wallet.ts
- src/pages/Governance/CreateProposal/Create.tsx
- src/pages/Governance/hooks/useSubmitStake.ts
- src/pages/Governance/hooks/useSubmitVote.ts
- src/pages/Transactions/Transaction.tsx
- yarn.lock
update code to match the BCS transaction changes https://github.com/aptos-labs/aptos-core/pull/3105/files#diff-2a5c7928e3087d9ae71840428528a606ce40925f7510f234798865bb20dabab4L16
> update sdk to 1.3.7

- src/pages/Governance/components/Header.tsx
> [Governance] hide wallet button for mobile

- src/ExplorerRoutes.tsx
- src/components/Nav.tsx
- src/components/NavMobile.tsx
> Governance sub menu

- src/api/hooks/useGetAccountResource.ts
- src/pages/Governance/Stake/Index.tsx
- src/pages/Governance/Stake/components/CreateOrEdit.tsx
- src/pages/Governance/Stake/components/EditContent.tsx
Getting a response can take some time (on busy networks) - adding a loading icon while client is waiting to the server response
> Add loading icon to staking page

- src/pages/Governance/Stake/Edit.tsx
- src/pages/Governance/Stake/components/EditOperator.tsx
- src/pages/Governance/Stake/components/EditVoter.tsx
- src/pages/Governance/Stake/components/IncreaseLockup.tsx
- src/pages/Governance/hooks/useSubmitIncreaseLock.ts
Owner can increase lockup through the UI
> increase lockup button

- src/pages/Governance/Proposal/Header.tsx
- src/pages/Governance/Proposals/Table.tsx
- src/pages/Governance/Types.ts
- src/pages/Governance/hooks/useGetProposal.tsx
> [Governance] add execution time

- src/ExplorerRoutes.tsx
- src/pages/Governance/Proposal/Index.tsx
- src/pages/Governance/Proposals/Index.tsx
- src/pages/Governance/Proposals/Table.tsx
- src/pages/Governance/hooks/useGetProposal.tsx
> [Governance] proposal url

- src/pages/Account/AccountInfo/Balance.tsx
- src/pages/Account/AccountInfo/Index.tsx
- src/pages/Account/AccountInfo/TokenBalance.tsx
Note that this is the new account page in development. It's not visible to users yet.
> [Explorer] account balance

- src/components/HashButton.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Transaction/Index.tsx
- src/pages/Transaction/Tabs.tsx
- src/pages/Transaction/Title.tsx
This PR addressed a few UI improvements @moonclavedev and I discussed about.
* mobile view for transaction title
* mobile view for Tabs: scrollable, smaller font
* clean up Tabs code
* back button for transaction page
* hash button link _blank
> [Explorer] ui improvement

- src/pages/Governance/Proposal/card/ParticipationBar.tsx
- src/pages/Governance/hooks/useGetCoinSupplyLimit.tsx
> [Explorer] fix participation

- src/pages/Account/Title.tsx
- src/pages/Transaction/Title.tsx
> [Explorer] change title color

- src/pages/NodeChecker/ConfigurationSelect.tsx
- src/pages/NodeChecker/EvaluationDisplay.tsx
- src/pages/NodeChecker/Index.tsx
This makes it render better on vertical monitors and mobile devices.
> [NHC] Add appropriate breakpoints for different viewport sizes

- src/pages/Account/AccountInfo/Balance.test.tsx
- src/pages/Account/AccountInfo/Balance.tsx
> Format APT balances correctly

- src/components/StyledTab.tsx
- src/components/StyledTabs.tsx
- src/pages/Transaction/Tabs.tsx
|Before|After|
|---|---|
|<img width="1479" alt="Screen Shot 2022-09-12 at 4 49 39 PM" src="https://user-images.githubusercontent.com/109111707/189778219-ed689235-bd28-48b2-9f94-5c2d35a3d3e7.png">|<img width="1485" alt="Screen Shot 2022-09-12 at 4 49 24 PM" src="https://user-images.githubusercontent.com/109111707/189778269-2cd55932-bcd5-4aaa-81f2-e02026b41853.png">|
> [Explorer] txn page: new tab

- src/api/hooks/useGetInDevMode.ts
- src/components/HashButton.tsx
- src/components/HashButtonCopyable.tsx
- src/components/StyledTab.tsx
- src/components/TransactionStatus.tsx
- src/pages/Transaction/Tabs.tsx
- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/Tabs/Components/ContentBox.tsx
- src/pages/Transaction/Tabs/Components/ContentRow.tsx
- src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
|Before|After|
|---|---|
|<img width="1487" alt="Screen Shot 2022-09-13 at 11 40 05 AM" src="https://user-images.githubusercontent.com/109111707/189984621-cb2e5ea3-29b8-4cfb-a86d-f53e3732d608.png">|<img width="1466" alt="Screen Shot 2022-09-13 at 11 40 33 AM" src="https://user-images.githubusercontent.com/109111707/189984635-5fbd9b60-95d2-4e1a-b455-a4116afa4a27.png">|
> [Explorer] new txn page: Overview

- src/components/JsonCard.tsx
- src/pages/Transaction/Tabs/Components/ContentRow.tsx
- src/pages/Transaction/Tabs/Components/EmptyValue.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
https://user-images.githubusercontent.com/109111707/190016113-ac635431-d040-4697-a3ef-a9b3ffec674c.mov
> [Explorer] add json card

- _redirects
> Add Netlify _redirects file.

- src/components/JsonCard.tsx
- src/pages/Transaction/Tabs.tsx
- src/pages/Transaction/Tabs/Components/CollapsibleCard.tsx
- src/pages/Transaction/Tabs/Components/CollapsibleCards.tsx
- src/pages/Transaction/Tabs/EventsTab.tsx
- src/pages/Transaction/hooks/useExpandedList.ts
https://user-images.githubusercontent.com/109111707/190068482-6befc24e-8c2d-4ed7-a64f-913ec2014e4a.mov
> [Explorer] new txn page: Events tab

- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/Tabs/ChangesTab.tsx
- src/pages/Transaction/Tabs/Components/CollapsibleCard.tsx
- src/pages/Transaction/Tabs/Components/CollapsibleCards.tsx
- src/pages/Transaction/Tabs/EventsTab.tsx
- src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/PayloadTab.tsx
- src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx
- src/pages/Transaction/Tabs/UnknownTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [Explorer] new txn page: add Payload tab and Changes tab

- src/components/IndividualPageContent/EmptyTabContent.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
- src/pages/Account/Tabs/OverviewTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
> [Explorer] apply new design to account page tabs

- .gitignore
- src/api/hooks/useGetCoinSupplyLimit.tsx
- src/pages/Account/AccountInfo/Balance.test.tsx
- src/pages/Account/AccountInfo/Balance.tsx
- src/pages/Governance/Proposal/card/ParticipationBar.tsx
- src/pages/LandingPage/Dashboard.tsx
- src/pages/LandingPage/NetworkInfo/ActiveValidators.tsx
- src/pages/LandingPage/NetworkInfo/Card.tsx
- src/pages/LandingPage/NetworkInfo/Index.tsx
- src/pages/LandingPage/NetworkInfo/MetricCard.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalStake.tsx
- src/pages/LandingPage/NetworkInfo/TotalSupply.tsx
> [Explorer] set up new home page

- package.json
- src/api/hooks/useGetCoinSupplyLimit.tsx
- src/api/hooks/useSubmitTransaction.ts
- src/api/index.ts
- src/pages/Block/data.ts
- src/pages/Governance/CreateProposal/Create.tsx
- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
- yarn.lock
* update aptos client version from `1.3.7` to `1.3.14`
* apply changes to work with the new version
> [Explorer] update aptos client

- src/constants.tsx
> [Explorer] set default network to testnet

- src/api/hooks/useGetBlock.ts
- src/api/hooks/useGetTPS.ts
- src/api/hooks/useGetTPSByBlockHeight.ts
- src/api/hooks/useGetValidatorSet.ts
- src/pages/Block/Index.tsx
- src/pages/LandingPage/NetworkInfo/ActiveValidators.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalStake.tsx
> [Explorer] home page metrics

- src/components/IndividualPageContent/EmptyTabContent.tsx
- src/pages/Account/Components/TokensTable.tsx
- src/pages/Account/Index.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Account/Tabs/TokensTab.tsx
> [Explorer] show owned tokens in account page

- src/pages/Block/Tabs/OverviewTab.tsx
- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
* apply feedback from #173 
* add one more field "Epoch"
> [Explorer] block page

- src/pages/Account/Tabs/TokensTab.tsx
- src/pages/LandingPage/NetworkInfo/ActiveValidators.tsx
- src/pages/LandingPage/NetworkInfo/Card.tsx
- src/pages/LandingPage/NetworkInfo/Index.tsx
- src/pages/LandingPage/NetworkInfo/MetricCard.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalStake.tsx
- src/pages/LandingPage/NetworkInfo/TotalSupply.tsx
- src/pages/LandingPage/NetworkInfo/TotalTransactions.tsx
- src/themes/colors/aptosColorPalette.ts
* home page: add TOTAL TRANSACTIONS
* home page: styling the cards
* small fix for token ownership graphql query
> [Explorer] homepage: add total transactions

- src/components/HashButtonCopyable.tsx
- src/pages/Account/BalanceCard.tsx
- src/pages/Account/Index.tsx
- src/pages/utils.tsx
> [Explorer] account balance card

- src/ExplorerRoutes.tsx
- src/api/hooks/useGetMostRecentBlocks.ts
- src/api/index.ts
- src/pages/Blocks/Index.tsx
- src/pages/Blocks/Table.tsx
> [Explorer] add blocks page

- src/components/Nav.tsx
- src/components/NavMobile.tsx
> [Explorer] nav bar: added new menu items

- src/components/IndividualPageContent/ContentRow.tsx
- src/components/Nav.tsx
- src/components/NavMobile.tsx
- src/pages/Token/Index.tsx
- src/pages/Token/Tabs/OverviewTab.tsx
> [Explorer] token overview

- src/api/hooks/useGetBlock.ts
- src/pages/layout/Search/Index.tsx
- src/pages/layout/Search/SearchBlockByHeight.tsx
- src/pages/layout/Search/SearchBlockByVersion.tsx
- src/pages/layout/Search/SearchInput.tsx
> [Explorer] add block search

- src/components/IndividualPageContent/ContentValue/GasFeeValue.tsx
- src/components/IndividualPageContent/LearnMoreTooltip.tsx
- src/pages/Account/Tabs/InfoTab.tsx
- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
- src/pages/Transactions/TransactionsTable.tsx
* organize tooltips for transaction page, account page, and block page
* show gas fee
> tooltips + gas fee

- src/components/HeadingSub.tsx
- src/components/IndividualPageContent/CollapsibleCard.tsx
- src/components/IndividualPageContent/ContentBox.tsx
- src/components/IndividualPageContent/ContentRow.tsx
- src/components/WalletButton.tsx
- src/pages/Governance/Proposals/Table.tsx
- src/pages/Governance/constants.tsx
- src/pages/LandingPage/NetworkInfo/Card.tsx
- src/pages/LandingPage/NetworkInfo/MetricCard.tsx
- src/pages/LandingPage/NetworkInfo/TotalTransactions.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/Title.tsx
- src/pages/Transactions/Index.tsx
- src/themes/colors/aptosColorPalette.ts
- src/themes/theme.ts
- Update Page Title Styling & Logic
- Bring updated Metric Card styling inline with current theme
- Updated color palette
- Address some mobile stacking issues
> Update Page Title logic, Metric Cards, Color Palette & Mobile Stacking

- src/api/hooks/useGetTPS.ts
- src/api/hooks/useGetTPSByBlockHeight.ts
- src/pages/LandingPage/LedgerInfo.tsx
- src/pages/LandingPage/NetworkInfo/TotalTransactions.tsx
This PR updating the re-query frequency from every 1s to every 10s for homepage metrics to avoid being rate limited.
> [Explorer] lower auto query frequency

- src/api/hooks/useGetCoinSupplyLimit.tsx
- src/constants.tsx
Remove AIT3 network from Explorer
> [Explorer] clean up ait3

- public/_redirects
Reverts aptos-labs/explorer#193
> Revert "redirect governance endpoints to governance foundation site"

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
> [Explorer] add receiver and amount for user transfer transactions

- src/pages/layout/Search/Index.tsx
- src/pages/layout/Search/SearchInput.tsx
https://user-images.githubusercontent.com/109111707/194185702-f50fb5a3-1840-4a39-9fc8-c43215191240.mov
> [Explorer] search on "Enter" key press

- src/components/TransactionStatus.tsx
- src/pages/Account/Tabs/TransactionsTab.tsx
- src/pages/Block/Tabs/TransactionsTab.tsx
- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
- src/pages/Transaction/Tabs/GenesisTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/StateCheckpointOverviewTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transactions/TransactionsTable.tsx
* reorder table columns
* status column: show icon only
* all transactions tables have the same columns set
> [Explorer] txns table

- src/api/hooks/useGetAccountTransactions.ts
- src/api/index.ts
- src/pages/Account/Tabs/TransactionsTab.tsx
- src/pages/Transactions/TransactionsTable.tsx
https://user-images.githubusercontent.com/109111707/194495422-3d808080-2dc7-4e85-bf9f-59559332641b.mov
> [Explorer] account transactions pagination

- src/pages/Transaction/Tabs/EventsTab.tsx
> [Explorer] add account address and creation number for event

- src/components/IndividualPageContent/JsonCard.tsx
- src/pages/LandingPage/NetworkInfo/ActiveValidators.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalStake.tsx
- src/pages/LandingPage/NetworkInfo/TotalSupply.tsx
* Home page metrics cards
* fix to 2 decimal for all the numbers
* update tooltips text
* code block card
* add copy button 
* small styling improvements
> [Explorer] ui improvements

- src/components/IndividualPageContent/JsonCard.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
* make scroll bar on the right side of the code block
* module card ui improvements based on dogfooding feedback: making `name` card title
> [Explorer] more ui improvements

- src/api/hooks/useGetUserTransactionVersions.ts
- src/api/index.ts
- src/pages/Transactions/AllTransactions.tsx
- src/pages/Transactions/Index.tsx
- src/pages/Transactions/UserTransactions.tsx
* In "Transactions" page, add a button to switch between "All Transactions" and "User Transactions"
* Fix search param for "All Transactions"
* Add "User Transactions" table with pagination. Note that we only show the recent 100 pages. It won't be meaningful to show all of them as there will be trillions of transactions. We will add some range selecting feature in the future.
* Fix all transactions last page
> [Explorer] User txns table

- src/constants.tsx
- src/pages/layout/NetworkSelect.tsx
> [Explorer] hide chain id

- src/pages/layout/NetworkSelect.tsx
Remove chain id implementation in the NetworkSelect button to fix hooks error. https://aptos-org.slack.com/archives/C040LV2NWQ4/p1665707919209319
> [Explorer] fix hooks error

- src/pages/LandingPage/Index.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalSupply.tsx
* update content as required for the metrics cards on home page
* show all transactions table (not user transactions) on home page
> [Explorer] update content

- src/api/hooks/useGetAccount.ts
- src/pages/Account/Error.tsx
- src/pages/Account/Index.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Account/Tabs/InfoTab.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
- src/pages/Account/Tabs/TokensTab.tsx
- src/pages/Account/Tabs/TransactionsTab.tsx
- src/pages/utils.tsx
Show error message on the page level (not tab level as previously) when account is not found.
> [Explorer] Account not found

- src/pages/utils.tsx
Fix: https://sentry.io/organizations/aptos-labs/issues/3645930905/?project=6249755&query=is%3Aunresolved
> [Explorer] fix sentry error

- src/pages/layout/Footer.tsx
Match Aptos Names footer with Privacy & Terms, remove contact emails & update Discord URL
> Match Aptos Names footer - removal of contact emails

- src/components/IndividualPageContent/JsonCard.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
> [Explorer] display transaction fucntion

- src/components/HashButton.tsx
- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Account/Index.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Account/Tabs/CoinsTab.tsx
> [Explorer] add account coins tab

- src/components/StyledTab.tsx
- src/pages/Transaction/Tabs.tsx
- src/pages/Transaction/Tabs/BalanceChangeTab.tsx
- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
- src/pages/Transaction/utils.tsx
- src/themes/colors/aptosColorPalette.ts
> [Explorer] transaction balance change tab

- src/api/hooks/useGetAccountTokens.ts
- src/api/hooks/useGetTokenActivities.ts
- src/pages/Account/Tabs/TokensTab.tsx
- src/pages/Token/Component/ActivitiesTable.tsx
- src/pages/Token/Tabs/ActivitiesTab.tsx
> [Explorer] add tokens pagination

- src/api/hooks/useGetANS.ts
- src/components/HashButton.tsx
- src/components/TitleHashButton.tsx
- src/pages/Account/Title.tsx
- src/pages/Transaction/Title.tsx
> [Explorer] show account ANS

- src/api/hooks/useGetANS.ts
- src/api/hooks/useGetSearchResults.ts
- src/pages/layout/Search/SearchInput.tsx
> [Explorer] search aptos names

- src/components/IndividualPageContent/JsonCard.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
- src/pages/Transaction/Tabs/ChangesTab.tsx
- src/pages/Transaction/Tabs/EventsTab.tsx
- src/pages/Transaction/Tabs/PayloadTab.tsx
> [Explorer] expand json cards by default

- src/api/hooks/useGetTPS.ts
- src/components/IndividualPageContent/ContentValue/CurrencyValue.tsx
- src/components/StyledTooltip.tsx
- src/pages/LandingPage/NetworkInfo/ActiveValidators.tsx
- src/pages/LandingPage/NetworkInfo/Card.tsx
- src/pages/LandingPage/NetworkInfo/MetricCard.tsx
- src/pages/LandingPage/NetworkInfo/TPS.tsx
- src/pages/LandingPage/NetworkInfo/TotalStake.tsx
- src/pages/LandingPage/NetworkInfo/TotalSupply.tsx
> [Explorer] Add peak TPS

- src/api/hooks/useGraphqlClient.tsx
- src/pages/Transactions/Index.tsx
show all transactions for devnet because indexer is not available right now for devnet
> [Explorer] show all transactions for devnet

- package.json
- src/api/hooks/useGetValidatorSet.ts
- src/api/hooks/useGetValidatorSetGeoData.ts
- src/pages/Validators/Components/Map.tsx
- src/pages/Validators/Components/MapMetrics.tsx
- src/pages/Validators/Index.tsx
- src/pages/Validators/ValidatorsMap.tsx
- yarn.lock
Dark mode
Smaller screen
Mobile
> [Explorer] validators map

- src/api/hooks/useGetEpochTime.ts
- src/pages/Validators/Components/Epoch.tsx
- src/pages/Validators/Components/MapMetrics.tsx
- src/pages/Validators/Components/MetricSection.tsx
- src/pages/Validators/Components/Text/Body.tsx
- src/pages/Validators/Components/Text/Subtitle.tsx
- src/pages/Validators/constants.ts
> [Explorer] add epoch time

- src/api/hooks/useGetStakingRewardsRate.ts
- src/components/StyledTooltip.tsx
- src/pages/Validators/Components/Epoch.tsx
- src/pages/Validators/Components/MapMetrics.tsx
- src/pages/Validators/Components/Staking.tsx
> [Explorer] add map staking section and tooltips

- src/components/CodeLineBox.tsx
- src/pages/Transaction/Tabs/Components/TransactionFunction.tsx
- src/pages/Validators/Components/LastEpochPerformanceTooltip.tsx
- src/pages/Validators/Components/Map.tsx
- src/pages/Validators/Components/RewardsPerformanceTooltip.tsx
> [Explorer] validators table tooltips

- src/pages/Validators/Components/MapMetrics.tsx
- src/pages/layout/Nav.tsx
- src/pages/layout/NavMobile.tsx
* show active validators count from on chain real time data in the map
* `/Validators` => `/validators`
> validators page quick fix

- public/index.html
> [Hotjar] install hotjar

- src/api/hooks/useGetAnalyticsData.ts
- src/api/hooks/useGetTPS.ts
> [Analytics] update peak tps data source

- src/api/hooks/useGetAnalyticsData.ts
- src/pages/Analytics/Charts/DailyContractDeployersChart.tsx
- src/pages/Analytics/Charts/DailyGasConsumptionChart.tsx
- src/pages/Analytics/Charts/DailyUserTransactionsChart.tsx
- src/pages/Analytics/MainnetAnalytics.tsx
- src/pages/Analytics/constants.ts
> [Analytics Page] add new charts

- src/pages/Transaction/Tabs/ChangesTab.tsx
> Changeset table

- src/pages/Analytics/Components/LineChart.tsx
- src/pages/Analytics/constants.ts
> [Analytics] chart dot styling

- package.json
- src/components/IndividualPageContent/JsonTreeCard.tsx
- src/components/IndividualPageContent/JsonViewCard.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
- src/pages/Token/Tabs/OverviewTab.tsx
- src/pages/Transaction/Tabs/ChangesTab.tsx
- src/pages/Transaction/Tabs/EventsTab.tsx
- src/pages/Transaction/Tabs/PayloadTab.tsx
- src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- yarn.lock
> New Json card

- src/components/IndividualPageContent/JsonViewCard.tsx
limit Json card to max height 500
> [Json Card] height

- src/pages/Account/Tabs/ModulesTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
- src/pages/Token/Tabs/OverviewTab.tsx
- src/pages/Transaction/Tabs/ChangesTab.tsx
- src/pages/Transaction/Tabs/EventsTab.tsx
- src/pages/Transaction/Tabs/PayloadTab.tsx
- src/pages/Transaction/Tabs/PendingTransactionOverviewTab.tsx
- src/pages/Transaction/Tabs/UnknownTab.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [Json Card] go live

- src/constants.tsx
The URL there currently works, but isn't recommended anymore.
> Use updated testnet URL

- src/api/hooks/useGetValidatorSet.ts
> [SEV] fix validator table

- src/pages/Validator/DetailCard.tsx
- src/pages/Validator/StakingBar.tsx
- src/pages/Validator/index.tsx
* create this bar in bare minimum. will add further UI and data source later. its gated in the dev mode
> [explorer][delegation] add the staking bar on the validator page

- src/ExplorerRoutes.tsx
- src/pages/Validators/Index.tsx
- src/pages/Validators/Table.tsx
- src/pages/Validators/ValidatorsTable.tsx
create the delegation node tab on the validators page and make sure it's properly gated.
will improve UI in future pr. 
https://user-images.githubusercontent.com/121921928/213314966-9d5ad0c5-74e7-4248-9b2e-8799ee22b8cb.mov
> [explorer][delegaiton] update validators page with the new delegatable tab

- src/index.tsx
- src/pages/Validators/Index.tsx
1. rm event listener on the index page, see [discussions](https://github.com/aptos-labs/explorer/pull/304#discussion_r1080594473)
2. last pr's accepted commit's bit messed up. lesson learned next time it's better to create a commit on the local env instead of directly on git. 
https://user-images.githubusercontent.com/121921928/213324537-3dc5064e-aa58-4d65-a289-21a592367ed4.mov
> [explorer][BE] rm event listener on the index page

- package.json
- src/components/WalletConnector/WalletButton.tsx
- src/components/WalletConnector/WalletMenu.tsx
- src/components/WalletConnector/WalletModel.tsx
- src/components/WalletConnector/index.tsx
- src/pages/layout/ConnectWallet.tsx
- src/pages/layout/Header.tsx
- src/pages/layout/index.tsx
this is just to make the flow work, since we copy pasted many logics directly from [ANS codebase](https://github.com/aptos-labs/aptos-names/tree/main/src/components/WalletConnector). a better way of handling this is to update wallet adaptor's UI package, which is already in my todo list. hopefully i can get it done by next week.
https://user-images.githubusercontent.com/121921928/213340827-05ab3149-45eb-4b81-abfa-ceb6d69ba88d.mov
> [explorer][delegation] refactor wallet connection flow

- src/components/IndividualPageContent/ContentRowSpaceBetween.tsx
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/index.tsx
Two things in this PR:
* implement what's reverted in #317 in a better way
* fix console warnings and errors in this the delegation validator page
> [Delegation] UI console errors fix

- src/components/StyledDialog.tsx
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeDialog.tsx
- src/pages/DelegatoryValidator/UnstakeDialog.tsx
- src/pages/DelegatoryValidator/utils.tsx
- src/pages/utils.tsx
https://user-images.githubusercontent.com/121921928/214727447-c192dbd0-d331-4bcd-8a22-731e9c03ec86.mov
> [explorer][delegation] refactor unstake dialog UI

- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/layout/Header.tsx
was trying to create a global state or abstract the `isMobile` logic out, but it's using mui theme to compute and can't live outside of the function in global state. 
https://user-images.githubusercontent.com/121921928/215158826-3fd8ecec-c4e4-44dc-83a9-7eaffada25b1.mov
> [explorer][delegation] make the change mobile friendly

- src/pages/Account/Components/AccountAllTransactions.tsx
- src/pages/Account/Index.tsx
- src/pages/Transactions/TransactionsTable.tsx
Re: https://aptos-org.slack.com/archives/C040LV2NWQ4/p1674950657260849
> [Account Txns] fix txn amount for address not starting with 0x

- src/api/hooks/useGetMainnetValidators.ts
> enforcing data nullability check

- src/pages/DelegatoryValidator/MyDepositsSection.tsx
https://user-images.githubusercontent.com/121921928/216196127-2a4d8442-6d9d-43a6-8816-b89aae4579f4.mov
> [explorer][delegation] for the sake of testing unstake UI

- src/components/IndividualPageContent/ContentRowSpaceBetween.tsx
- src/components/Table/GeneralTableHeaderCell.tsx
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/Validators/ValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/216193645-5eb174e8-9271-4d22-bffb-9ef24b59d175.mov
> [explorer][delegation] add tooltips

- src/pages/DelegatoryValidator/Components/TimeDurationIntervalBar.tsx
this screen recording is a bit long, feel free to fast forward to see the time change without refreshing the page. 
https://user-images.githubusercontent.com/121921928/216201765-af4734e1-012d-4679-88c4-92e6b65a29d0.mov
> [explorer][delegation] refresh time countdown interval bar every min

- src/pages/layout/index.tsx
https://user-images.githubusercontent.com/121921928/217400691-08b4272b-63e9-4cf3-b216-28c43ae81dd8.mov
> [explorer][delegation] add banner for new feature launch

- src/api/hooks/useGetDelegatorStakeInfo.ts
- src/api/index.ts
- src/constants.tsx
> [explorer][delegation] add view function query to get stake info per delegator

- src/api/hooks/useGetDelegationNodeInfo.ts
- src/api/index.ts
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/StakeDialog.tsx
- src/pages/Validators/Table.tsx
- src/pages/Validators/ValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/219227248-86c091f9-c94f-467b-8642-8e5358e546ee.mov
> [explorer][delegation] add operator commission from sc view function

- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/Title.tsx
- src/pages/DelegatoryValidator/index.tsx
1. add skeleton loading to the page together and refactor the skeleton size
2. verify skeleton loading mobile works
3. add tooltip to my deposits section header
4. dialog bottom text, make them more compact & my deposits section button smaller
https://user-images.githubusercontent.com/121921928/220225681-a808b495-d593-4e66-98be-838478292f2d.mov
https://user-images.githubusercontent.com/121921928/220225707-03085eed-cfc2-457f-b399-989f469d8388.mov
https://user-images.githubusercontent.com/121921928/220225709-cebc0902-7c44-47d6-9276-49ecf7942736.mov
https://user-images.githubusercontent.com/121921928/220225712-2eff07ec-d60e-413a-9f09-69d02a7692e9.mov
> [explorer][delegation] nits

- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
https://user-images.githubusercontent.com/121921928/220251604-1526b66e-e508-4a2b-aece-6bfde9900104.mov
> [explorer][delegation] refresh the page after txn submitted

- src/pages/Validators/ValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/220244812-6a99ecd5-ad98-4dcc-8357-cdea6e55a509.mov
> [explorer][delegation] only enable validator table row click if its whitelisted delegation nodes

- src/api/hooks/useGetAccountResource.ts
- src/api/hooks/useGetCoinSupplyLimit.tsx
- src/api/hooks/useGetEpochTime.ts
- src/api/hooks/useGetStakingRewardsRate.ts
- src/api/hooks/useGetValidatorSet.ts
- src/pages/DelegatoryValidator/index.tsx
Reverts aptos-labs/explorer#361
> Revert "[explorer] simplify useGetAccountResource"

- package.json
- src/components/IntervalBar.tsx
- src/pages/DelegatoryValidator/Components/TimeDurationIntervalBar.tsx
- src/pages/Validators/Components/Epoch.tsx
- src/pages/utils.tsx
- yarn.lock
https://user-images.githubusercontent.com/121921928/220244021-c7004e9e-74cb-4598-973d-4cebe33ebd79.mov
https://user-images.githubusercontent.com/121921928/220244025-86b28a22-1898-4dd5-8d0e-cdc53eade7f5.mov
> [explorer] consolidate interval bar using react-countdown

- src/pages/DelegatoryValidator/MyDepositsSection.tsx
https://user-images.githubusercontent.com/121921928/220700186-cfa63772-8361-44f6-9dde-6b6248c86c76.mov
> [explorer][delegation] hide mydeposits section if there's no deposits made

- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Index.tsx
https://user-images.githubusercontent.com/121921928/220458835-3c3ac05f-a4d8-48dd-be74-19f7dc04844c.mov
> [explorer][BE] separate delegation validators table from validators table 

- src/api/hooks/useGetValidators.ts
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/220992723-04cceaca-4d81-4ef3-babe-e8b63abe7781.mov
> [explorer][delegation] add accrued rewards data query per delegation pool

- src/api/hooks/useGetDelegatorStakeInfo.ts
- src/pages/Validators/DelegationValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/221021998-f59032e4-199a-473d-adea-c0db358dd06e.mov
> [explorer][delegation] promote staking feature visibility

- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Tabs.tsx
1. rename tab url name
2. layout change on delegation validators page
3. fix accrued rewards number display
4. remove rewards perf on delegation validators table
https://user-images.githubusercontent.com/121921928/221288370-9ec8c60d-9593-4476-8e1a-c472148b574b.mov
https://user-images.githubusercontent.com/121921928/221288377-a822e255-5d59-4eee-b6f0-0d8cf701a379.mov
> [explorer][delegation] fix accrued rewards number and other nits

- src/pages/Account/Tabs/ModulesTab.tsx
add "view code" | "write" tabs
> [explorer] add viewcode & write tabs to modules

- src/pages/Account/Tabs/ModulesTab.tsx
> [explorer] fix modules sidebar header

- package.json
- src/index.tsx
- src/pages/Account/Components/AccountAllTransactions.tsx
- yarn.lock
Set up A/B testing with StatSig and add a demo experiment.
> [AB Testing] add demo experiment

- src/api/hooks/useGetValidators.ts
- src/constants.tsx
- src/pages/Validators/Tabs.tsx
- src/pages/Validators/ValidatorsTable.tsx
https://user-images.githubusercontent.com/121921928/224184358-5e5f7927-2118-48cb-9deb-03ede87949e8.mov
> [network] add previewnet

- src/api/hooks/useGetDelegatedStakeOperationActivities.ts
> [delegation] sort delegation activities by transaction version to make the computation accurate

- src/constants.tsx
https://user-images.githubusercontent.com/121921928/224382400-8e5c4021-562a-41d0-a2e3-72be5738ce7c.mov
> [previewnet] update pfn url to use https

- src/api/hooks/useSubmitTransaction.ts
directly use error msg instead of parsing it through so that no need to be dependent on strict format of the error msg.
> [delegation] update snackbar error msg

- package.json
- src/pages/Account/Tabs/ModulesTab.tsx
- yarn.lock
In follow-up PRs, I will:
- Divide code in `ModulesTab` into a few smaller components
- Maybe prompt a toast on transaction submitted? Need design, and may need to change `useSubmitTransaction`
- Verify edge cases work, for example, `code::publish_package`
> [explorer] write contract

- src/pages/Account/Tabs/ModulesTab.tsx
> [explorer] add copy code button

- src/pages/Account/Tabs/ModulesTab.tsx
> [explorer] add line number to move code blocks

- src/pages/Account/Tabs/ModulesTab.tsx
> [explorer] modules page ui minor adjustment

- src/pages/Account/Tabs/ModulesTab.tsx
- src/utils.ts
> [explorer] add entry functions count and bytecode size to module header

- package.json
- src/components/SideDrawer.tsx
- src/pages/Validators/StakingBanner.tsx
- src/pages/Validators/StakingDrawer.tsx
- src/themes/theme.ts
- yarn.lock
https://user-images.githubusercontent.com/121921928/226000134-e34bbcd6-bb7f-41de-8d4d-3ab99aa4078d.mov
> [delegation] add side panel

- src/pages/Account/Tabs/ModulesTab.tsx
before expanding
after expanding
> [explorer] expand code

- src/constants.tsx
- src/pages/Account/Tabs/ModulesTab.tsx
> [explorer] hide write contracts to earlydev mode

- src/pages/Account/Error.tsx
> fix text overflow when screen size is small

- src/api/hooks/useGetDelegationNodeInfo.ts
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
> [delegation] change to delegated voting power

- src/pages/Account/Tabs/ModulesTab.tsx
This PR moves the view code feature from behind the dev feature flag.
Check out https://deploy-preview-432--aptos-explorer.netlify.app/account/0x1/modules
> [explorer] graduate the view code feature in modules page

- src/pages/Account/Tabs/ModulesTab.tsx
tsia
| -- | -- |
| <img width="1141" alt="Screenshot 2023-03-29 at 12 12 42 PM" src="https://user-images.githubusercontent.com/121921928/228643769-2758071f-00ca-4a13-abb7-ac82b339d7af.png"> | <img width="1125" alt="Screenshot 2023-03-29 at 12 12 09 PM" src="https://user-images.githubusercontent.com/121921928/228643799-3ba2fed5-0b35-4a4c-9ced-ecba913601c0.png"> |
> make font size a bit smaller

- src/pages/DelegatoryValidator/hooks/useAmountInput.tsx
| before | after | 
| -- | -- | 
| <img width="226" alt="Screenshot 2023-03-30 at 12 44 27 PM" src="https://user-images.githubusercontent.com/121921928/228947407-0c0fe2c7-5ad0-4b28-ad7c-70427565e2ff.png"> | <img width="449" alt="Screenshot 2023-03-30 at 12 44 01 PM" src="https://user-images.githubusercontent.com/121921928/228947440-065171de-433f-4fa1-9e9b-d15bf89bfe47.png"> |
> [delegation][EZ] fix max amount in error msg

- package.json
as title. I want to show the most recent change for Giselle to review
> [explorer] update ans package version for the banner

- src/__tests__/utils.test.ts
- src/api/hooks/useGetANS.ts
- src/utils.ts
- yarn.lock
Let's say an user's ANS name is `name.apt`, previous we can only search it by `name` or `name.apt`, this PR let user search by `name`, `name.`, `name.a`, `name.ap`, `name.apt`
> [GP-12] support ANS search with partial APT suffix

- src/pages/Validators/StakingDrawer.tsx
https://user-images.githubusercontent.com/121921928/230513322-42070bad-76c7-4211-970d-2f16e8893d78.mov
https://docs.google.com/document/d/1xfBnQ4uafp4C2-6lxhjmNoVMVvVy3KvoyqfXx3Vpo7o/edit#heading=h.77ca3ddwm0m4
> [delegation] upd faq

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
so we don't have to format manually now.
> use husky to auto lint after commit

- package.json
- pnpm-lock.yaml
> update aptos package dependency to 1.8.2

- src/pages/Account/Tabs/ModulesTab/WriteContract.tsx
> [explorer] style write contract

- package.json
- pnpm-lock.yaml
- src/index.tsx
> add msafe wallet to explorer

- src/pages/DelegatoryValidator/utils.tsx
WithdrawStakeEvent is not part of the calculation. removing it
> [delegation] rm WithdrawStakeEvent

- src/api/hooks/useGetDelegationNodeInfo.ts
- src/api/index.ts
- src/pages/DelegatoryValidator/Components/ValidatorStatusIcon.tsx
- src/pages/DelegatoryValidator/Title.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Tabs.tsx
> [delegation] add validator state

- src/api/hooks/useGetAccountAllTransactions.ts
https://aptos-org.slack.com/archives/C03MN5F7WUV/p1681410699899869
> update account txn query to load large load of txn

- src/api/client.ts
- src/pages/Account/Error.tsx
- src/pages/DelegatoryValidator/index.tsx
gracefully handle 429 with an error msg
https://aptos-org.slack.com/archives/C03EP0XM99D/p1681330225916179
> handle 429

- src/index.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx
- src/pages/DelegatoryValidator/WalletConnectionDialog.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Index.tsx
- src/pages/Validators/StakingBanner.tsx
- src/pages/Validators/Tabs.tsx
- src/pages/layout/Header.tsx
> Statsig logging

- src/pages/Validators/DelegationValidatorsTable.tsx
https://deploy-preview-479--aptos-explorer.netlify.app/validators?network=mainnet
> [delegation] fix table sorting

- src/api/hooks/useGetValidatorSet.ts
- src/api/hooks/useGetValidators.ts
- src/utils.ts
https://deploy-preview-481--aptos-explorer.netlify.app/validators/delegation?network=mainnet
reference: https://github.com/aptos-labs/internal-ops/pull/1239
> [delegation] fix address leading zero issue

- src/api/index.ts
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/pages/Account/Tabs/ModulesTab/Tabs.tsx
Refactor WriteContract to be Contract s.t. it can be reused for both read and write cases
> [explorer] support read contracts

- src/pages/Account/Tabs/ModulesTab/Contract.tsx
> [explorer] fix modules dark mode

- src/pages/Account/Tabs/ModulesTab/Contract.tsx
> [explorer] order contract sidebar

- package.json
- pnpm-lock.yaml
- src/pages/layout/NavMobile.tsx
> enable wallet connection on mobile

- src/pages/Account/Tabs/ModulesTab/ViewCode.tsx
| -- | -- |
| <img width="1221" alt="Screenshot 2023-04-26 at 3 35 04 PM" src="https://user-images.githubusercontent.com/121921928/234717374-b2ea54d4-c2ab-40f1-a415-fd16db5137d1.png"> | <img width="1108" alt="Screenshot 2023-04-26 at 3 35 09 PM" src="https://user-images.githubusercontent.com/121921928/234717386-cdd2280b-9d9a-424e-ad22-2678975a234c.png"> |
> add package name to view code

- src/pages/Transaction/Tabs/BlockMetadataOverviewTab.tsx
| -- | -- |
| <img width="1102" alt="Screenshot 2023-04-26 at 4 20 53 PM" src="https://user-images.githubusercontent.com/121921928/234722901-bc60e75e-d726-4f1f-a5ce-6aefe500c50e.png"> | <img width="1302" alt="Screenshot 2023-04-26 at 4 20 42 PM" src="https://user-images.githubusercontent.com/121921928/234722916-483fae28-ebe8-4b22-93d8-d50a9f8f3cd0.png"> |
> fix txn overview box padding

- src/api/hooks/useGetNumberOfDelegators.ts
https://deploy-preview-499--aptos-explorer.netlify.app/validators?network=mainnet
> fix num delegator graphql query

- src/pages/Account/Tabs/ModulesTab/Contract.tsx
without default values, submitting the form could potentially submit `{..., arguments: undefined}` which fails the view function call. after the change, `{..., arguments: []}` won't fail the view function call.
besides, display the error message if view function call fails
> [explorer] fix parameterless view function call

- src/pages/Validators/Tabs.tsx
https://deploy-preview-505--aptos-explorer.netlify.app/
feedback: https://aptos-org.slack.com/archives/C040LV2NWQ4/p1683561604375549
> change validators tab default to all nodes

- src/components/StyledTab.tsx
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/pages/Account/Tabs/ModulesTab/Tabs.tsx
- src/pages/Account/Tabs/ModulesTab/ViewCode.tsx
"Code" tab:
"Code" tab, mobile view:
"Run" & "View" tab:
"Run" tab, mobile view:
"View" tab, mobile view:
> Update style and add mobile view for Modules page 

- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/themes/theme.ts
Validate that the args are not empty before submission.
Screenshot:
I changed the `theme` because the disabled button text color is not readable
> [Contract] Validate the args, make sure it's not empty

- src/pages/Account/Index.tsx
https://deploy-preview-523--aptos-explorer.netlify.app/
> remove ans banner for non mainnet

- src/api/hooks/useGetANS.ts
- src/components/HashButton.tsx
fix ans name query race condition by using `useQuery` instead of `useEffect`
https://aptos-org.slack.com/archives/C040LV2NWQ4/p1683841215530359
> fix ans name query race condition

- src/pages/Transaction/utils.tsx
https://aptoslabs.pagerduty.com/incidents/Q2VT0AQI59UIS8
> add new coin transfer function

- renovate.json
https://docs.renovatebot.com/configuration-options/#group
https://stackoverflow.com/questions/66471226/renovate-combine-all-updates-to-one-branch-pr
> update renovate config to group together dependencies updates into single PR

- src/pages/LandingPage/TransactionsPreview.tsx
- src/pages/LandingPage/UserTransactionsPreview.tsx
> update navigation in view all transactions

- src/pages/Account/Tabs/ModulesTab/index.tsx
Open Contract Run & View feature in PROD
> Open Contract Run & View feature in PROD

- src/api/hooks/useGetANS.ts
- src/components/HashButton.tsx
- src/components/TitleHashButton.tsx
- src/pages/DelegatoryValidator/DetailCard.tsx
- src/pages/DelegatoryValidator/Title.tsx
- src/pages/Validators/ValidatorsTable.tsx
https://aptoslabs.pagerduty.com/incidents/Q3GI53T03EJXT3
> [sev] only use primary name lookup for validators ans association

- pnpm-lock.yaml
- src/api/hooks/useGetDelegatorStakeInfo.ts
- src/api/hooks/useGetMostRecentBlocks.ts
- src/api/hooks/useGetSearchResults.ts
- src/api/hooks/useGetValidators.ts
- src/global-config/feature-selection.ts
- src/global-config/network-selection.ts
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/pages/Account/Tabs/ModulesTab/Tabs.tsx
- src/pages/Account/Tabs/ModulesTab/ViewCode.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/index.tsx
- src/pages/Transactions/Index.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Index.tsx
- src/pages/layout/Search/Index.tsx
```
jillxu@Jills-MacBook-Pro explorer % pnpm lint
> aptos-explorer@0.0.1 lint /Users/jillxu/Documents/GitHub/explorer
> tsc --noEmit && eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
```
> fix lint warning

- src/utils.ts
view function only accept the number type for u8, u16, u32
> Fix view function bug on u8, u16, u32 types

- src/pages/Analytics/Charts/DailyActiveUserChart.tsx
Updating tooltip to be more accurate
> Update active accounts tooltip

- src/ExplorerRoutes.tsx
- src/api/hooks/useGetANS.ts
- src/api/hooks/useGetSearchResults.ts
- src/pages/Account/Index.tsx
- src/pages/Account/Tabs.tsx
- src/pages/Account/Tabs/CoinsTab.tsx
- src/pages/Account/Tabs/InfoTab.tsx
- src/pages/Account/Tabs/ResourcesTab.tsx
- src/pages/Account/Tabs/TokensTab.tsx
- src/pages/Account/Tabs/TransactionsTab.tsx
- src/pages/Account/Title.tsx
Example:  http://localhost:3000/object/0xab530f9ac297701fb3c51672899b045c953a8e3762801b7926f736f5f2fc6bb2/coins?network=testnet
search bar:
Object page:
Resources tab:
> Add basic object support

- package.json
- pnpm-lock.yaml
- src/api/hooks/useGetAccountTokens.ts
- src/pages/Token/Index.tsx
- src/pages/Token/Tabs/OverviewTab.tsx
http://localhost:3000/token/0xab7e7754e7a7533edcbf698f1cee998296e438f1c84e5db9d4c74dcafe02b36c/1?network=mainnet
> Token V2 typings and sdk update

- src/pages/Account/Components/AccountAllTransactions.tsx
http://localhost:3000/account/0x3d78ef065f4dd973dd755b33028137184cd72a76410c3252936e3be502142b33?network=mainnet
loads
> Remove stale experiment

- src/pages/Account/Components/AccountAllTransactions.tsx
- src/pages/Account/hooks/useLogEventWithBasic.ts
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Index.tsx
- src/pages/Validators/StakingBanner.tsx
- src/pages/Validators/Tabs.tsx
- src/pages/layout/Header.tsx
Summary
We want to put all logs through this helper function rather than calling statsig directly because we want to share some logic checking for statsig initialization.
Test Plan
`tsc` and ci
> Move all logs to use shared function

- src/pages/Token/Tabs/OverviewTab.tsx
- src/pages/utils.tsx
See link working with non-valid URI
http://localhost:3000/token/0x2a6ead9b31c15f82b78ab3e988c0ebb7c663d40bcefa02ee099da094952aa402/0/overview?network=testnet
> Fix for token uri's not being valid

- src/pages/Validators/ValidatorsTable.tsx
http://localhost:3000/validators/delegation?network=testnet
> Filter out 0 voting power

- src/api/hooks/useGetSearchResults.ts
This will save some network calls and prevent confusion
> Only search for .apt names when detecting .apt

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
> Move IC to Prod

- src/api/hooks/useGetDelegationNodeInfo.ts
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/utils.tsx
- src/pages/Validators/DelegationValidatorsTable.tsx
https://app.incident.io/aptos/incidents/20
> fix delegated amount to be the same as voting power

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
https://github.com/aptos-labs/explorer/assets/129789810/1169b8cc-2f10-4b57-a92c-2aaf3821a228
> Support okx wallet

- .prettierignore
- src/api/index.ts
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- Fixes errors associated with errors that are from invalid ledger versions
- Allows running transactions through mobile in app browsers, even if the experience isn't the greatest
- Stops formatting world.json, so pnpm fmt can be added to CI
> Cleanup view/run functions

- src/global-config/GlobalConfig.tsx
Context here: https://aptos-org.slack.com/archives/C036V52D9U4/p1705011305237719.
> Set x-indexer-client header

- src/global-config/GlobalConfig.tsx
> Set x-indexer-client header for all clients

- src/api/hooks/useGraphqlClient.tsx
```
curl -X POST \
-H "Content-Type: application/json" \
--data '{ "query": "query MyQuery { coin_activities(limit: 1) { transaction_version } }" }' \
https://indexer.random.aptoslabs.com/v1/graphql
{"data":{"coin_activities":[{"transaction_version":0}]}}%  
```
> add randomnet indexer api

- src/pages/Account/Index.tsx
- tsconfig.json
Check out https://deploy-preview-675--aptos-explorer.netlify.app/account/0x628e72def46bc247908f0b06367bfbf744a50328e429a97632941035ef50a63/transactions?network=mainnet&page=1
> [accounts] Fix accounts page to handle missing leading 0s

- src/constants.tsx
should just call it previewnet
> update previewnet name

- src/pages/Account/Components/CodeSnippet.tsx
we cannot verify the code, not that we have no option but to verify it :P
> fix double negation in the description

- src/utils.ts
> Error handling for non-hex source code

- src/pages/layout/index.tsx
Last PR missed adding to dropdown
> [wallets] Add bitget wallet to dropdown

- package.json
- pnpm-lock.yaml
- src/api/hooks/useGetAccount.ts
- src/api/hooks/useGetAccountModule.ts
- src/api/hooks/useGetAccountModules.ts
- src/api/hooks/useGetAccountResource.ts
- src/api/hooks/useGetAccountResources.ts
- src/api/hooks/useGetAccountTokens.ts
- src/api/hooks/useGetAccountTransactions.ts
- src/api/hooks/useGetBlock.ts
- src/api/hooks/useGetDelegationNodeInfo.ts
- src/api/hooks/useGetMostRecentBlocks.ts
- src/api/hooks/useGetNetworkChainIds.ts
- src/api/hooks/useGetTPS.ts
- src/api/hooks/useGetTransaction.ts
- src/pages/Analytics/NetworkInfo/TotalTransactions.tsx
- src/pages/LandingPage/TransactionsPreview.tsx
- src/pages/Transaction/Index.tsx
- src/pages/Transactions/AllTransactions.tsx
The issue was in `useGetAccountResource`. For some reason splatting `options` wasn't working (?????). Tested it a few times, the object was coming through props, but the hook wasn't respecting it. Ended up passing it directly. In the process I upgraded `react-query` from 4 to 5 for better maintenance. 
After / Before Demo
https://github.com/aptos-labs/explorer/assets/694324/9d6586ad-caba-481b-a122-48ba1e09dcc5
> Fixes account page loading state issue

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
https://github.com/aptos-labs/explorer/assets/19931667/169faf38-fd9e-4ec5-8643-37a4e3f188b3
Testnet signatures are not working yet, so it fails. But should work when testnet is fixed
> Add AptosConnect on testnet and devnet

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
1. Using Zeta
2. Having the option show up on every network (otherwise it will not update well)
> Update for AptosConnect testing

- src/pages/layout/Footer.tsx
Fixes discord link to point to https://discord.com/invite/aptosnetwork
> Fix discord link

- analytics/README.md
- analytics/daily_active_users.sql
- analytics/daily_average_gas_unit_price.sql
- analytics/daily_contract_deployers.sql
- analytics/daily_deployed_contracts.sql
- analytics/daily_gas_from_user_transactions.sql
- analytics/daily_max_tps_15_blocks.sql
- analytics/daily_new_accounts_created.sql
- analytics/daily_user_transactions.sql
- analytics/mau_signers.sql
- analytics/max_tps_15_blocks_in_past_30_days.sql
- analytics/validator_stats.sql
Now that google's [public bigquery dataset](https://console.cloud.google.com/marketplace/product/bigquery-public-data/crypto-aptos-mainnet-us) is available, here is the logic for the JSONs that are generated that for aggregate data on explorer
> Queries for analytics

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
This reverts commit 3f00115b1106a6801217af0a9794ec72feb782f1.
> Revert "Downgrade husky (#742)"

- src/api/hooks/useSubmitTransaction.ts
- src/pages/layout/index.tsx
There are currently some cacheing issues in adapter. Will put this hack in for testing and remove once we fix adapter
> Fix for AptosConnect breaking on network switches

- src/ExplorerRoutes.tsx
- src/pages/layout/Fallback.tsx
- src/pages/layout/index.tsx
Hello!
Introduce code splitting based on routes
Before:
After:
Thanks!
> Code splitting based on routes

- package.json
- pnpm-lock.yaml
* update msafe wallet version to fix url fetch issue
> feat: update msafe wallet

- src/pages/Transaction/Tabs/BalanceChangeTab.tsx
- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
- src/pages/Transaction/utils.tsx
Went down two separate rabbit holes, took way longer than needed 😓 
Tested with transaction: 0x2ab4b504b1e356ae5539b80f88c38aac0685df5884a7d08497512919d25eac67
> Adds fungible assets balance changes

- src/api/hooks/useGetAccountTokens.ts
- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Account/Components/TokensTable.tsx
- src/pages/Account/Tabs/CoinsTab.tsx
Adds coin and token types to their respective tables.
> Table updates

- .github/workflows/lint-and-test.yaml
Fixes the issue described in https://github.com/pnpm/action-setup/issues/135, which is breaking our CI.
See CI.
> Update pnpm/action-setup to v4

- package.json
- pnpm-lock.yaml
Upgrading husky fixed the pre-commit silent failures.
> Upgrades husky

- package.json
- pnpm-lock.yaml
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/pages/DelegatoryValidator/WalletConnectionDialog.tsx
- src/pages/layout/Header.tsx
- src/pages/layout/NavMobile.tsx
https://github.com/aptos-labs/explorer/assets/25761639/cafc517a-704d-4d6b-985f-42aad5574783
> Add education screens to wallet selector

- src/api/hooks/useGetAccountAllTransactions.ts
- src/pages/Transaction/utils.tsx
Positive test case: 
https://deploy-preview-776--aptos-explorer.netlify.app/txn/1022270660/balanceChange?network=mainnet
> Removes distinct from fungible events query

- src/pages/Transaction/utils.tsx
example txn to test against: 0x3940661171bdd12eb2eb97579bff5534bacf7f204b6ccf25e87e85c4621d5331
> fix balance change tab on txn to skip null amount

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
Open block doesn't see significant traffic here, so I'm removing it due to some vulnerabilities pulled in that don't necessarily need to apply.
> [deps] Update testing updates, remove overrides, remove openblock

- package.json
- pnpm-lock.yaml
- src/pages/layout/index.tsx
Fewcha is less than 0.5% of users of the explorer, so removing it should be okay.
```sh
pnpm audit
No known vulnerabilities found
```
> [deps] Remove fewcha to remove security vulnerabilities

- src/pages/layout/Search/Index.tsx
> [search] Hide deleted object if it's not a deleted object

- src/pages/Transaction/helpers.tsx
- src/pages/Validators/Components/Epoch.tsx
- src/pages/Validators/Components/Staking.tsx
- src/pages/Validators/StakingDrawer.tsx
Updates all the tooltips!  They were out of date
> Tooltip updates

- src/pages/layout/Search/Index.tsx
- src/pages/utils.tsx
> [search] Fix regex on addresses, show better results

- src/pages/Transaction/Tabs/Components/TransactionFunction.tsx
Resolves https://github.com/aptos-labs/explorer/issues/816
> [transaction overview] Fix multisig function name

- src/components/IndividualPageContent/ContentValue/GasFeeValue.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
resolves https://github.com/aptos-labs/explorer/issues/825
> [gas] Fix gas units showing

- src/pages/Account/Tabs/InfoTab.tsx
An example is here:
https://deploy-preview-829--aptos-explorer.netlify.app/account/0xfcca5a63a68598ae6d56324df47ebb03c375e8ad82a9d7a1bf6520f16e5377a6/info?network=mainnet
> [account] Show if the authentication key is rotated

- src/api/hooks/useGetValidators.ts
- src/constants.tsx
- src/pages/Validators/Tabs.tsx
- src/pages/Validators/ValidatorsTable.tsx
Remove sentry errors about a non-existent network.
> [previewnet] Remove previewnet

- src/api/hooks/useGetAccountAllTransactions.ts
- src/api/hooks/useGetAccountTokens.ts
- src/api/hooks/useGetDelegatedStakeOperationActivities.ts
- src/api/hooks/useGetNumberOfDelegators.ts
- src/components/IndividualPageContent/LearnMoreTooltip.tsx
- src/components/Table/VerifiedCell.tsx
- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Account/Tabs/CoinsTab.tsx
- src/pages/FungibleAsset/Error.tsx
- src/pages/FungibleAsset/Index.tsx
- src/pages/FungibleAsset/Tabs.tsx
- src/pages/FungibleAsset/Tabs/InfoTab.tsx
- src/pages/FungibleAsset/Tabs/TransactionsTab.tsx
- src/pages/FungibleAsset/Title.tsx
- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
- src/pages/Transaction/utils.tsx
- src/utils.ts
Adds the same thing to account coin balances as it did to balance changes
> Add verification to balances page

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/helpers.tsx
Example:
https://deploy-preview-838--aptos-explorer.netlify.app/txn/1831578045?network=mainnet
> [user transactions] Show fee payer on explorer transaction page

- src/components/TitleHashButton.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
- src/pages/Transaction/utils.tsx
- src/pages/Transactions/TransactionsTable.tsx
1. Remove contract address as counterparty, is confusing
2. Add FA support and object transfer support
3. Support all basic coin transfers
> [counterparty] Fix counterparty

- src/api/hooks/useGetANS.ts
Based on what's being called a lot right now, here are some more labels
Also add some from [defillama](https://defillama.com/chain/Aptos)
> more address labels

- src/components/Table/VerifiedCell.tsx
> [VerifiedCell] remove not needed reason

- src/api/hooks/useGetANS.ts
- src/pages/layout/Search/Index.tsx
I started with fuzzy matching, but it gave too many results, so it is only exact match.
I also removed some confusing labels, 0xa was mostly a placeholder.
> [search] Add exact search for known names

- src/pages/Account/Components/AccountAllTransactions.tsx
The aggregate query sometimes timesout for accounts, because there are too many transactions.
Resolves: https://github.com/aptos-labs/explorer/issues/793
> [account] Show up to 10k transactions

- src/pages/Token/Tabs/OverviewTab.tsx
- src/pages/utils.tsx
Example:
https://explorer.aptoslabs.com/token/0x9616b8657c21e3fa61f687ca76d33aac6dd7491d0d923029266ac834baf42247?network=mainnet 
https://deploy-preview-850--aptos-explorer.netlify.app/token/0x9616b8657c21e3fa61f687ca76d33aac6dd7491d0d923029266ac834baf42247?network=mainnet
> [token] Fix loading of ipfs images

- src/pages/Account/Components/AccountAllTransactions.tsx
|before|after|
|--|--|
|<img width="1419" alt="image" src="https://github.com/user-attachments/assets/3bbc99eb-6db0-4000-b42e-f1f35bca146f">|<img width="1423" alt="image" src="https://github.com/user-attachments/assets/07690c34-1593-4cdc-9260-7df476bd3abd">|
> [Account] add margin around transactions count

- src/pages/Transactions/TransactionsTable.tsx
|before|after|
|--|--|
|<img width="137" alt="image" src="https://github.com/user-attachments/assets/c9edc9c6-bdb9-4f11-bc6a-e65cd6a809aa">|<img width="150" alt="image" src="https://github.com/user-attachments/assets/da26d38b-29dc-4684-b2ef-0d1646e501bb">|
> fix gas format in transactions table

- src/api/hooks/useGetANS.ts
A few more labels but some i'm less confident on
> more labels

- src/api/index.ts
- src/pages/DelegatoryValidator/Components/TimeDurationIntervalBar.tsx
1. Make block page pull blocks concurrently
2. Make validator delegation only go to 14 days
> Small fixes

- src/components/IndividualPageContent/ContentValue/GasFeeValue.tsx
- src/pages/Transactions/TransactionsTable.tsx
Resolves https://github.com/aptos-labs/explorer/issues/880
> [gas] Make gas changes look the same as balance changes with colors

- src/api/hooks/useGetANS.ts
add more labels to reflect thalaswap v2 release
> more thala labels

- src/pages/Transaction/utils.tsx
Resolves https://github.com/aptos-labs/explorer/issues/892
> [transactions] Add source contract for multisig transactions that apply

- src/pages/layout/Search/Index.tsx
Resolves https://github.com/aptos-labs/explorer/issues/899
Resolves https://github.com/aptos-labs/explorer/issues/856
> [search] Fix address lookup if no owned objects

- src/components/Table/GeneralTableRow.tsx
- src/index.tsx
- src/pages/Blocks/Table.tsx
- src/pages/Transactions/Components/TransactionTypeTooltip.tsx
- src/pages/Transactions/TransactionsTable.tsx
- src/utils.ts
This fixes most of the console errors (except one I can't seem to fix in the balance changes).
It additionally fixes strange navigation on the blocks page
> Fix console errors

- src/api/hooks/useGetANS.ts
- src/components/Table/VerifiedCell.tsx
- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Coin/Title.tsx
- src/pages/FungibleAsset/Title.tsx
- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
Example: Martian wallet https://deploy-preview-902--aptos-explorer.netlify.app/account/0x50f657118cb11ef52d34c4a1800c472abefee7b41f9670abcf2f8a8464067fc1?network=mainnet
Example scams:
https://deploy-preview-902--aptos-explorer.netlify.app/txn/1891719111/balanceChange?network=mainnet
https://deploy-preview-902--aptos-explorer.netlify.app/coin/0x50788befc1107c0cc4473848a92e5c783c635866ce3c98de71d2eeb7d2a34f85::aptos_coin::AptosCoin?network=mainnet
> Add martian wallet - more anti-scam measures

- src/api/hooks/useGetANS.ts
> [addresses] Add pontem wallet fees address

- .prettierignore
- public/robots.txt
Allow webcrawlers
Disallow searchability for non mainnet networks
> [robots.txt] Allow web crawlers

- src/api/hooks/useGetANS.ts
- src/api/hooks/useGetCoinList.ts
- src/components/Table/VerifiedCell.tsx
- src/pages/FungibleAsset/Tabs/InfoTab.tsx
- src/pages/layout/Search/Index.tsx
Fixes search, now it does prefix search on most things > 4 characters
> [addresses] Add BUIDL and fix prefix search / naming on search

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [UserTransactionOverviewTab] fix secondary signers conditional rendering

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
set up a template to add event interpretation (aka "action") to txn events tab, and add thalaswap actions as the first ones.
see https://deploy-preview-908--aptos-explorer.netlify.app/txn/1916163127?network=mainnet
#865
> [EventsTab] add txn actions and use thala as an example

- analytics/apt_supply.sql
- analytics/daily_active_users.sql
- analytics/daily_average_gas_unit_price.sql
- analytics/daily_contract_deployers.sql
- analytics/daily_deployed_contracts.sql
- analytics/daily_gas_from_user_transactions.sql
- analytics/daily_max_tps_15_blocks.sql
- analytics/daily_new_accounts_created.sql
- analytics/daily_user_transactions.sql
- analytics/mau_signers.sql
Tweak where clause to make SQL slightly more efficient
Also add in example query for APT supply
> Optimize analytics sql

- src/api/hooks/useGetCoinHolders.ts
- src/api/hooks/useGetFaMetadata.ts
- src/pages/Coin/Index.tsx
- src/pages/Coin/Tabs.tsx
- src/pages/Coin/Tabs/HoldersTab.tsx
- src/pages/FungibleAsset/Index.tsx
- src/pages/FungibleAsset/Tabs.tsx
- src/pages/FungibleAsset/Tabs/HoldersTab.tsx
- src/pages/FungibleAsset/Tabs/InfoTab.tsx
- src/pages/FungibleAsset/Tabs/TransactionsTab.tsx
Adds holders, as one of the requested items for https://github.com/aptos-labs/explorer/issues/906
> [coin/fa] Add holders tab

- src/pages/Transaction/Tabs/Components/TransactionActions.tsx
Fixes those little links that point to address, when they should point to account.
> [nft actions] Fxi links from `address` to `account`

- src/components/Table/VerifiedCell.tsx
- src/pages/Coin/Title.tsx
- src/pages/FungibleAsset/Title.tsx
Ensures that the random anti-scam rules don't apply to devnet/testnet
> [verification] Disable autobanning testnet tokens

- src/components/Table/VerifiedCell.tsx
> [verification] Remove one token from autoban

- src/api/hooks/useGetANS.ts
- src/components/Table/VerifiedCell.tsx
- src/pages/layout/Search/Index.tsx
Adds verification for emojicoins
> [verification] Verify emojicoin

- src/components/Table/VerifiedCell.tsx
This handles verification of FAs that don't necessarily have verification specifically set, but the coins they migrated do.
> [verification] Verify FA matched with already verified coins

- src/components/HashButton.tsx
- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
> Fixes coin symbols for emojicoins, and fixes showing all verified coins in the balances table

- src/pages/Transaction/Tabs/Components/TransactionFunction.tsx
> [transactions] Identify devnet and testnet faucet calls

- package.json
- pnpm-lock.yaml
> [deps] Patch cross-spawn

- package.json
- pnpm-lock.yaml
The previous variable version caused some issues on upgrade, this locks them into specific versions.
> [deps] Update and lock wallet adapter to a version

- src/constants.tsx
> [validation] Validate MYCO

- src/pages/Coin/Tabs.tsx
- src/pages/FungibleAsset/Tabs.tsx
These are incomplete as they don't look like the rest of the transactions table.  Needs to be redone on the backend, so will just mark as beta for now.
> [coin] Mark holders and transactions as beta

- src/components/Table/VerifiedCell.tsx
- src/constants.tsx
> verify ama fa

- src/constants.tsx
> add more CEX labels

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
https://deploy-preview-972--aptos-explorer.netlify.app/txn/2155364527?network=mainnet
> [UserTransactionOverviewTab] explain liquidswap/pancakeswap/cellana

- src/api/hooks/useGetANS.ts
- src/components/TitleHashButton.tsx
- src/constants.tsx
- src/pages/layout/Search/Index.tsx
> Add more labels

- src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx
- src/pages/utils.tsx
> chore: fix some typos

- src/api/hooks/useGetCoinList.ts
Following https://docs.panora.exchange/developer/token-list
> [getCoinList] Get all coins, including ones not show in Panora UI

- src/pages/Account/Error.tsx
Resolves https://github.com/aptos-labs/explorer/issues/970
> [account] Improve no account message

- src/pages/Coin/Tabs/InfoTab.tsx
- src/pages/FungibleAsset/Tabs/InfoTab.tsx
Resolves https://github.com/aptos-labs/explorer/issues/867
> [coin/fa] Show market cap as supply * panora price

- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [UserTransactionOverviewTab] better dex rendering in swap actions

- src/pages/Transaction/Tabs/BalanceChangeTab.tsx
https://deploy-preview-982--aptos-explorer.netlify.app/txn/2191304806/balanceChange?network=mainnet
before, it is very difficult to tell what's the sum balance change look like
after, go to "aggregated" and people are able to easily tell
> [BalanceChangeTab] add aggregated balance change

- src/constants.tsx
> [constants] fix thalaswap v2 address

- src/api/hooks/useGetCoinPairedFa.ts
- src/api/hooks/useGetCoinSupplyLimit.ts
- src/api/hooks/useGetFaMetadata.ts
- src/api/hooks/useGetFaPairedCoin.ts
- src/api/hooks/useGetFaSupply.ts
- src/components/Table/VerifiedCell.tsx
- src/pages/Analytics/NetworkInfo/TotalSupply.tsx
- src/pages/Coin/Index.tsx
- src/pages/FungibleAsset/Index.tsx
Adds spinners already built in for pages that weren't waiting on loading
> [coin/fa] Add loading showing for view function loads

- src/components/IdenticonImg.tsx
> [fix] Disable profile pictures

- package.json
- pnpm-lock.yaml
> [deps] Update Vite

- src/api/hooks/useGetFaPairedCoin.ts
- src/pages/FungibleAsset/Index.tsx
> [view] Fix view function caching

- src/api/hooks/useGetBlock.ts
- src/api/hooks/useGetMostRecentBlocks.ts
- src/api/hooks/useGetTPSByBlockHeight.ts
- src/api/index.ts
- src/api/v2.ts
- src/pages/Block/Tabs.tsx
- src/pages/Block/Tabs/OverviewTab.tsx
- src/pages/Block/Tabs/TransactionsTab.tsx
- src/pages/Blocks/Index.tsx
- src/pages/Blocks/Table.tsx
- src/pages/layout/Search/Index.tsx
- navigation between blocks
- counts of transactions
> [block] Slight UX improvements on blocks

- src/constants.tsx
> [coin] Add Acred

- src/constants.tsx
> [constants] add msafe fees

- src/pages/layout/Search/Index.tsx
Skips searching for objects unless the account doesn't exist.
> [search] Delay searching for objects until all other queries fail

- src/api/hooks/useGetAccountResource.ts
- src/pages/Account/Components/MovePackageManifest.tsx
- src/pages/Account/Tabs/ModulesTab/Packages.tsx
- src/pages/Account/Tabs/ModulesTab/Tabs.tsx
- src/pages/Account/Tabs/ModulesTab/ViewCode.tsx
Closes https://github.com/aptos-labs/explorer/issues/949
> display package metadata

- src/pages/FungibleAsset/Tabs/HoldersTab.tsx
Resolves https://github.com/aptos-labs/explorer/issues/1002
> [holders] Fix undefined listings on holders page

- src/pages/Transaction/Tabs/BalanceChangeTab.tsx
Resolves https://github.com/aptos-labs/explorer/issues/999
> [balancechange] fix invalid symbol crash

- src/pages/Transaction/Tabs/Components/CoinBalanceChangeTable.tsx
Resolves https://github.com/aptos-labs/explorer/issues/920
> [balance changes] Allow copying balance changes

- src/api/hooks/useGetANS.ts
- src/components/TitleHashButton.tsx
- src/pages/Account/Title.tsx
Resolves https://github.com/aptos-labs/explorer/issues/849
> [accounts] Add ANS and labels together

- package.json
- pnpm-lock.yaml
> [deps] Upgrade vite to 6.1.0

- src/components/Table/VerifiedCell.tsx
- src/constants.tsx
This was just prior to launches, now that there are launches, we don't have to mark them automatically as banned.
> [verification] Remove USDT and USDC from auto scam list

- src/api/hooks/useGetAssetMetadata.ts
- src/api/hooks/useGetCoinMetadata.ts
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [UserTransactionOverviewTab] fix decimals for unsupported coins in actions

- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> [UserTransactionOverviewTab] support Cetus swap action

- src/constants.tsx
> [verify] Verify propbase nexus

- src/pages/Account/Tabs/ModulesTab/Contract.tsx
Resolves https://github.com/aptos-labs/explorer/issues/1030
> [run-contract] Fix txn redirect on run contract page

- src/constants.tsx
> [verify] Verify pact

- src/constants.tsx
> [verify] Verify pact labs

- src/api/hooks/useGetDelegatedStakingPoolList.ts
- src/api/hooks/useGraphqlQueryPaginated.ts
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
Adds proper pagination, and fetching more to the list.
We will need to add pagination on the table at some point, but for now it properly pulls all the delegation validators.
Will need to follow up on other pages
> [validators] Fix pagination of delegated validators list

- src/constants.tsx
> [verify] Fix typo with hhttps -> https

- src/pages/Validators/Tabs.tsx
> remove the beta sign on delegation

- src/components/OutOfCommissionPoolsBanner.tsx
- src/pages/Validators/Delegation/EnhancedValidatorsPage.tsx
- src/pages/Validators/Index.tsx
> out of commission banner

- src/api/hooks/delegations/useGetDelegatedStaking.ts
- src/components/OutOfCommissionPoolsBanner.tsx
Resolves https://github.com/aptos-labs/explorer/issues/1057
> [validators] Fix staking banner from crashing validators page

- src/constants.tsx
> [verify] Verify rewardy token

- src/pages/Transaction/utils.tsx
Fixes this pesky 0 APT balance when transferring FA APT.
Note, includes secondary stores
Resolves https://github.com/aptos-labs/explorer/issues/1060
Resolves https://github.com/aptos-labs/explorer/issues/1034
> [balance] Add FA balance for APT tracking on transactions

- src/constants.tsx
Verifies Cassia Banyan Tree for Props
> [verify] Verify CassiaBanyanTree

- src/constants.tsx
> [verify] Verify binance.us

- src/constants.tsx
> Verify monkeys

- package.json
- pnpm-lock.yaml
This reverts commit 41153a0de8448ddd525c021cac75de893dab6102.
> Revert "[deps] Update @sentry/react to v9 (#1026)"

- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
label hyperfluid dex and explain hyperfluid swap action
https://deploy-preview-1075--aptos-explorer.netlify.app/txn/2509642362?network=mainnet
> [UserTransactionOverviewTab] support hyperfluid

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
render econia swap
lzUSDC -> APT https://deploy-preview-1078--aptos-explorer.netlify.app/txn/2522971619?network=mainnet
> [UserTransactionOverviewTab] support econia

- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
hyperfluid rebranded to hyperion https://x.com/hyperion_xyz/status/1904869103644639347
> update labels hyperfluid -> hyperion

- package.json
- pnpm-lock.yaml
> [deps] Upgrade vite to 6.2.4

- src/pages/Validators/Delegation/EnhancedDelegationValidatorsTable.tsx
Cleans up sort, and colors for commission
> Cleanup enhanced delegation

- package.json
- pnpm-lock.yaml
- src/index.tsx
- src/polyfills.ts
Fixes `Buffer is undefined` issue on coins page
> Fix polyfill for Buffer

- src/pages/Validators/Tabs.tsx
Shows the beta delegation page for anyone to see.
> [validators] Move new page to public, with beta tag

- src/components/WalletDeprecationBanner.tsx
- src/pages/Account/Tabs/ModulesTab/Contract.tsx
- src/pages/LandingPage/Index.tsx
- src/pages/Validators/Delegation/EnhancedValidatorsPage.tsx
- src/pages/Validators/Index.tsx
- Remove github discussion banner
- Remove commission change banner
- Add wallet deprecation banner
> [banner] Replace github discussion banner with wallet deprecation

- package.json
- pnpm-lock.yaml
Updates vite and others for security purposes
> [deps] Run pnpm update

- src/pages/layout/Search/Index.tsx
Resolves https://github.com/aptos-labs/explorer/issues/969
> [search] Don't clear search box until there are results

- src/constants.tsx
Add rKGEN, AMI, CELL, VIBE to manually verified list
> Add new tokens to manually verified list

- src/pages/Account/Index.tsx
Accounts can not exist and have state, so error is not helpful, and is just confusing.  Removing it now
> [account] Remove warning about account not existing

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
update Hyperion Swap Event Name for UserTransactionOverviewTab
> [UserTransactionOverviewTab] update hyperion swap event name

- src/constants.tsx
- src/pages/Transaction/Tabs/BalanceChangeTab.tsx
> [coins] Fix APT logo to be CDN instead of github

- src/api/hooks/delegations/useGetDelegationState.ts
- src/components/OutOfCommissionPoolsBanner.tsx
- src/pages/DelegatoryValidator/MyDepositsSection.tsx
- src/pages/DelegatoryValidator/StakeOperationDialog.tsx
- src/pages/DelegatoryValidator/StakingBar.tsx
- src/pages/DelegatoryValidator/TransactionSucceededDialog.tsx
- src/pages/LandingPage/GithubDiscussionsBanner.tsx
- src/pages/Validators/Delegation/EnhancedDelegationValidatorsTable.tsx
- src/pages/Validators/Delegation/EnhancedTabs.tsx
- src/pages/Validators/Delegation/hooks/useValidatorDelegationData.ts
- src/pages/Validators/DelegationValidatorsTable.tsx
- src/pages/Validators/Tabs.tsx
- src/pages/layout/Header.tsx
- src/utils.ts
> [wallet] Fix white screen with pontem

- src/constants.tsx
> [fa] Verify CAS1045

- src/pages/layout/index.tsx
> [wallets] First attempt at fixing msafe

- src/pages/layout/index.tsx
> [msafe] remove wrong app id, leave just the appurl

- package.json
- pnpm-lock.yaml
> revert wallet adapter to previous version

- package.json
- pnpm-lock.yaml
> Revert wallet adapter

- src/constants.tsx
Add label for Kana Perps mainnet address
> Add label for Kana Perps address

- src/components/HashButton.tsx
Ensures that we un-truncate truncated addresses in buttons.
Resolves https://github.com/aptos-labs/explorer/issues/1135
> [account] Fix truncated addresses

- src/utils.ts
> [address] Handle parsing undefined address

- src/pages/LandingPage/CoinToFAMigrationBanner.tsx
- src/pages/LandingPage/Index.tsx
> show fa migration banner

- src/api/hooks/useGetCoinList.ts
- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> Add flipster to addresses

- src/constants.tsx
> [verify] Add tapp

- src/components/IndividualPageContent/ContentRow.tsx
- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
add support of Hyperion Add/Remove Liqiudity Event for UserTransactionOverviewTab
add support of Tapp Swap/Add/Remove Liqiudity Event for UserTransactionOverviewTab
add support of Liquid Staking Event of Kofi, TruFi, ThalaLSD and Amnis for UserTransactionOverviewTab
apply flex-wrap for multiple actions
> [UserTransactionOverviewTab] add support to Tapp, hyperion, Kofi, TruFi, Amnis, ThalaLSD and minor UI adjustment

- package.json
- pnpm-lock.yaml
> [deps] Update form-data

- src/pages/utils.tsx
The page for https://explorer.aptoslabs.com/coin/0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002?network=mainnet is not accessible.
fixed #1173
> [utils] Fix regex in isValidStruct

- src/constants.tsx
> [addresses] Add UFC Strike

- src/api/hooks/useGraphqlClient.tsx
- src/constants.tsx
- src/global-config/GlobalConfig.tsx
- src/pages/layout/NetworkSelect.tsx
- src/pages/layout/index.tsx
You can see the network here - http://localhost:3000/?network=decibel
But hiding it from the network selector so we don't confuse people
> Add decibel

- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
Support parsing for Hyperion claim actions
OT: wanted to add support for Tapp but their ClaimFeeEvent got no token metadata just amount.
> [UserTransactionOverviewTab] Support fees and rewards claim for Hyperion

- src/constants.tsx
- src/pages/Transaction/Tabs/UserTransactionOverviewTab.tsx
> add thalaswap cl label

- src/pages/Account/Components/CoinsTable.tsx
- src/pages/Account/Tabs/CoinsTab.tsx
> [CoinTables]Remove migrate button

- package.json
- pnpm-lock.yaml
> [dpes] Upgrade axios

- src/api/hooks/useGetStakingRewardsRate.ts
- src/constants.tsx
> [rewards] Fix rewards rate from on-chain data

- src/constants.tsx
> [verify] MKL

- src/api/hooks/useGraphqlClient.tsx
- src/constants.tsx
> Rename shelbydevnet to shelbynet
